# OpenWillis Face Demo

Run this notebook with the `Python (airest-voice)` kernel after setup from `README.md`.

This notebook runs the demo call exactly as requested.

In [3]:
import pandas as pd

pd.set_option("display.max_columns", None)

# facial_expressivity

## normalize = True

In [ ]:
import openwillis.face as ef

framewise_loc, framewise_disp, summary = ef.facial_expressivity(
	filepath = 'video.mov', 
	baseline_filepath = 'sample_data/baseline.mp4', 
	bbox_list = [], 
	base_bbox_list = [], 
	frames_per_second = 30, 
	normalize = True, 
	align = False, 
	rolling_std_seconds = 3, 
	split_by_speaking = False)

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1779292723.265889 10644939 gl_context.cc:357] GL version: 2.1 (2.1 Metal - 89.4), renderer: Apple M3 Pro
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
W0000 00:00:1779292723.269404 11279139 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1779292723.273151 11279145 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1779292723.290290 11279141 landmark_projection_calculator.cc:186] Using NORM_RECT without IMAGE_DIMENSIONS is only supported for the square ROI. Provide IMAGE_DIMENSIONS or use PROJECTION_MATRIX.
I0000 00:00:1779292728.716155 10644939 gl_context.cc:357] GL version: 2.1 (2.1 Metal - 89.4), renderer: Apple M3 Pro
W0000 00:00:1779292728.719392 11279379 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1779292728.724141 11279379 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

In [10]:
framewise_loc

     lmk001_x  lmk002_x  lmk003_x  lmk004_x  lmk005_x  lmk006_x  lmk007_x  \
0         0.0  0.006496  0.000089 -0.042407  0.006654  0.004096 -0.004326
1         0.0  0.005665  0.001383 -0.041335  0.005709  0.004155 -0.001291
2         0.0  0.004379 -0.000209 -0.043567  0.004409  0.002430 -0.004730
3         0.0  0.005084  0.000935 -0.041371  0.005344  0.003924 -0.001644
4         0.0  0.004640  0.000728 -0.042335  0.004775  0.003231 -0.002636
..        ...       ...       ...       ...       ...       ...       ...
639       0.0  0.012351  0.009473 -0.017473  0.015791  0.021150  0.034213
640       0.0  0.012284  0.009120 -0.017921  0.015748  0.020926  0.033451
641       0.0  0.011049  0.008034 -0.019926  0.014365  0.019223  0.030950
642       0.0  0.013457  0.009508 -0.017233  0.017020  0.022013  0.033706
643       0.0  0.013662  0.009340 -0.018099  0.017055  0.021580  0.031860

     lmk008_x  lmk009_x  lmk010_x  lmk011_x  lmk012_x  lmk013_x  lmk014_x  \
0   -0.371953 -0.007383 -0.007285 -0.008818 -0.000487 -0.001669 -0.003095
1   -0.360126 -0.003039 -0.002863 -0.007290 -0.000245 -0.000858 -0.001403
2   -0.364190 -0.006648 -0.006246 -0.010921 -0.000318 -0.001185 -0.002202
3   -0.357696 -0.002934 -0.002317 -0.006093 -0.000508 -0.001312 -0.002100
4   -0.360851 -0.004075 -0.003553 -0.008069 -0.000443 -0.001194 -0.001997
..        ...       ...       ...       ...       ...       ...       ...
639 -0.310951  0.044532  0.049792  0.061963 -0.002063 -0.002891 -0.002594
640 -0.313517  0.043645  0.048957  0.060297 -0.001963 -0.002751 -0.002564
641 -0.316952  0.040842  0.046148  0.057658 -0.001940 -0.002790 -0.002736
642 -0.315006  0.043664  0.049023  0.060911 -0.002138 -0.003245 -0.003326
643 -0.317997  0.040708  0.045529  0.055696 -0.002028 -0.003238 -0.003377

     lmk015_x  lmk016_x  lmk017_x  lmk018_x  lmk019_x  lmk020_x  lmk021_x  \
0   -0.004490 -0.003985 -0.004113 -0.005185 -0.007904  0.004382 -0.045005
1   -0.001489 -0.001163 -0.000976 -0.000775 -0.001458  0.004294 -0.045045
2   -0.002604 -0.002168 -0.002130 -0.002411 -0.004590  0.002875 -0.046396
3   -0.002172 -0.001959 -0.002057 -0.002357 -0.004290  0.003719 -0.044923
4   -0.002133 -0.001786 -0.001825 -0.002092 -0.004023  0.003328 -0.045596
..        ...       ...       ...       ...       ...       ...       ...
639 -0.002569 -0.003956 -0.005652 -0.007039 -0.008788  0.010454 -0.035370
640 -0.002334 -0.003584 -0.005234 -0.006671 -0.008828  0.010230 -0.035950
641 -0.002766 -0.003900 -0.005558 -0.007079 -0.009667  0.009075 -0.037047
642 -0.003799 -0.005024 -0.006751 -0.008451 -0.011312  0.011235 -0.035502
643 -0.004512 -0.005585 -0.007128 -0.008654 -0.011283  0.011486 -0.036221

     lmk022_x  lmk023_x  lmk024_x  lmk025_x  lmk026_x  lmk027_x  lmk028_x  \
0   -0.551837 -0.227305 -0.277785 -0.325227 -0.389037 -0.184323 -0.291161
1   -0.539457 -0.219424 -0.269118 -0.315918 -0.377395 -0.176911 -0.282041
2   -0.552380 -0.224635 -0.274215 -0.320723 -0.382624 -0.182272 -0.285724
3   -0.546181 -0.219458 -0.268844 -0.315059 -0.376338 -0.177204 -0.280095
4   -0.548159 -0.221637 -0.271168 -0.317542 -0.379066 -0.179325 -0.283047
..        ...       ...       ...       ...       ...       ...       ...
639 -0.470843 -0.176192 -0.225167 -0.270502 -0.328267 -0.133963 -0.231458
640 -0.473700 -0.178438 -0.227474 -0.272827 -0.330852 -0.136146 -0.233507
641 -0.477398 -0.181096 -0.230123 -0.275554 -0.334197 -0.138988 -0.236640
642 -0.475598 -0.179539 -0.228879 -0.274397 -0.332504 -0.136908 -0.234205
643 -0.481881 -0.182003 -0.231442 -0.277184 -0.335484 -0.139337 -0.238005

     lmk029_x  lmk030_x  lmk031_x  lmk032_x  lmk033_x  lmk034_x  lmk035_x  \
0   -0.239166 -0.340449 -0.374332 -0.427921 -0.201544 -0.388902 -0.576803
1   -0.231126 -0.329674 -0.362185 -0.417290 -0.192457 -0.376386 -0.564491
2   -0.235494 -0.333214 -0.366002 -0.423248 -0.195453 -0.380439 -0.574282
3   -0.230243 -0.327120 -0.359533 -0.417604 -0.193766 -0.373692 -0.568432
4   -0.232903 -0.330355 -0.362888 -0.419589 -0.194202 -0.376962 -0.569481
..        ...       ...       ...       ...       ...       ...       ...
639 -0.181259 -0.278553 -0.310954 -0.369220 -0.195230 -0.326085 -0.505672
640 -0.183384 -0.280693 -0.313249 -0.371662 -0.196358 -0.328683 -0.508186
641 -0.186587 -0.283864 -0.316440 -0.374812 -0.198339 -0.332372 -0.511898
642 -0.183909 -0.281613 -0.314351 -0.373558 -0.200495 -0.330203 -0.511712
643 -0.187225 -0.285582 -0.318237 -0.376747 -0.199602 -0.333355 -0.516534

     lmk036_x  lmk037_x  lmk038_x  lmk039_x  lmk040_x  lmk041_x  lmk042_x  \
0   -0.484939 -0.256318 -0.062344 -0.054803 -0.127309 -0.169787 -0.101744
1   -0.473617 -0.252352 -0.063079 -0.054668 -0.128427 -0.170750 -0.102212
2   -0.479936 -0.257123 -0.063634 -0.055559 -0.129584 -0.172302 -0.103746
3   -0.474149 -0.254104 -0.063341 -0.055361 -0.128828 -0.171093 -0.103122
4   -0.475858 -0.255221 -0.063451 -0.055285 -0.129022 -0.171417 -0.103184
..        ...       ...       ...       ...       ...       ...       ...
639 -0.420066 -0.227736 -0.061274 -0.054725 -0.124098 -0.164085 -0.099972
640 -0.422422 -0.229420 -0.061446 -0.054887 -0.124496 -0.164888 -0.100482
641 -0.425793 -0.231060 -0.061480 -0.054899 -0.124475 -0.164825 -0.100391
642 -0.424517 -0.231479 -0.062370 -0.056669 -0.126800 -0.168551 -0.103284
643 -0.428580 -0.232485 -0.062193 -0.056286 -0.126626 -0.168108 -0.102827

     lmk043_x  lmk044_x  lmk045_x  lmk046_x  lmk047_x  lmk048_x  lmk049_x  \
0   -0.139622 -0.238948 -0.036558 -0.043381 -0.455924 -0.157409 -0.160437
1   -0.140268 -0.235443 -0.037560 -0.044104 -0.443387 -0.154089 -0.163750
2   -0.141957 -0.237255 -0.038423 -0.044992 -0.449030 -0.158798 -0.165330
3   -0.140828 -0.235342 -0.037476 -0.043862 -0.443172 -0.155292 -0.163274
4   -0.141135 -0.236027 -0.038147 -0.044692 -0.445703 -0.156677 -0.164177
..        ...       ...       ...       ...       ...       ...       ...
639 -0.135328 -0.228983 -0.029395 -0.032617 -0.385770 -0.121523 -0.145393
640 -0.136268 -0.229763 -0.029673 -0.032782 -0.388269 -0.122969 -0.146615
641 -0.136147 -0.230203 -0.030910 -0.034098 -0.391268 -0.125106 -0.147470
642 -0.140155 -0.234400 -0.028633 -0.031565 -0.389094 -0.123762 -0.146933
643 -0.139565 -0.234131 -0.028528 -0.031700 -0.392902 -0.125572 -0.148130

     lmk050_x  lmk051_x  lmk052_x  lmk053_x  lmk054_x  lmk055_x  lmk056_x  \
0   -0.165296 -0.405885 -0.042615 -0.342221 -0.409082 -0.503535 -0.118816
1   -0.167930 -0.399044 -0.042706 -0.329023 -0.396351 -0.492504 -0.110454
2   -0.170151 -0.405360 -0.044265 -0.334934 -0.401597 -0.503742 -0.116334
3   -0.167863 -0.401497 -0.042611 -0.330342 -0.396222 -0.498094 -0.112664
4   -0.168869 -0.402593 -0.043530 -0.333267 -0.399043 -0.500313 -0.114896
..        ...       ...       ...       ...       ...       ...       ...
639 -0.146964 -0.368002 -0.025249 -0.277729 -0.340647 -0.422424 -0.066904
640 -0.148227 -0.370442 -0.025567 -0.279725 -0.342928 -0.425069 -0.068120
641 -0.149225 -0.372630 -0.027181 -0.282018 -0.345673 -0.428411 -0.070362
642 -0.148594 -0.374128 -0.024536 -0.279611 -0.343274 -0.426129 -0.067815
643 -0.149916 -0.375061 -0.025043 -0.282175 -0.346629 -0.432336 -0.069821

     lmk057_x  lmk058_x  lmk059_x  lmk060_x  lmk061_x  lmk062_x  lmk063_x  \
0   -0.192515 -0.276553 -0.533158 -0.123907 -0.081857 -0.219337 -0.197264
1   -0.185285 -0.273897 -0.519317 -0.126923 -0.082399 -0.219779 -0.197836
2   -0.190305 -0.275789 -0.527573 -0.128356 -0.084096 -0.221460 -0.199383
3   -0.185302 -0.273510 -0.521599 -0.126381 -0.082373 -0.219574 -0.197292
4   -0.187657 -0.274453 -0.521894 -0.127193 -0.083098 -0.220105 -0.198075
..        ...       ...       ...       ...       ...       ...       ...
639 -0.136882 -0.262919 -0.479362 -0.111347 -0.070186 -0.211100 -0.189203
640 -0.139009 -0.264429 -0.483621 -0.112531 -0.071093 -0.212151 -0.190516
641 -0.142238 -0.264814 -0.487541 -0.113376 -0.071919 -0.212042 -0.190481
642 -0.139445 -0.269529 -0.492099 -0.112934 -0.071194 -0.217832 -0.196057
643 -0.142336 -0.269267 -0.495101 -0.113999 -0.072256 -0.217257 -0.195456

     lmk064_x  lmk065_x  lmk066_x  lmk067_x  lmk068_x  lmk069_x  lmk070_x  \
0   -0.438888 -0.163493 -0.248417 -0.258202 -0.298657 -0.471363 -0.273674
1   -0.425656 -0.166479 -0.236075 -0.245797 -0.292777 -0.458958 -0.264416
2   -0.432225 -0.168443 -0.242600 -0.252266 -0.299546 -0.468363 -0.270865
3   -0.426993 -0.166262 -0.238648 -0.248352 -0.294557 -0.463237 -0.266639
4   -0.429680 -0.167065 -0.241575 -0.251182 -0.296858 -0.465797 -0.269163
..        ...       ...       ...       ...       ...       ...       ...
639 -0.366988 -0.148585 -0.190127 -0.196862 -0.223948 -0.396145 -0.205913
640 -0.369424 -0.149976 -0.191701 -0.198393 -0.225764 -0.398666 -0.207494
641 -0.372020 -0.150813 -0.193780 -0.200474 -0.228627 -0.401407 -0.209907
642 -0.369746 -0.150771 -0.191297 -0.197850 -0.225385 -0.399184 -0.206980
643 -0.373213 -0.152065 -0.193256 -0.200181 -0.231393 -0.403685 -0.211033

     lmk071_x  lmk072_x  lmk073_x  lmk074_x  lmk075_x  lmk076_x  lmk077_x  \
0   -0.486373 -0.519013 -0.059230 -0.112276 -0.153899 -0.111278 -0.207454
1   -0.473831 -0.506774 -0.059606 -0.113338 -0.154743 -0.113317 -0.208412
2   -0.480910 -0.517027 -0.060144 -0.114574 -0.156304 -0.114936 -0.210039
3   -0.475109 -0.511264 -0.059941 -0.113953 -0.155219 -0.112977 -0.208098
4   -0.477531 -0.513466 -0.059945 -0.114114 -0.155517 -0.113704 -0.208706
..        ...       ...       ...       ...       ...       ...       ...
639 -0.414050 -0.443742 -0.059090 -0.110697 -0.149356 -0.098686 -0.199756
640 -0.416676 -0.446425 -0.059243 -0.111097 -0.150124 -0.099798 -0.200926
641 -0.419725 -0.449688 -0.059157 -0.110999 -0.149995 -0.100610 -0.200800
642 -0.417537 -0.447690 -0.060598 -0.113653 -0.153821 -0.100320 -0.206595
643 -0.421549 -0.452749 -0.060243 -0.113260 -0.153322 -0.101546 -0.206019

     lmk078_x  lmk079_x  lmk080_x  lmk081_x  lmk082_x  lmk083_x  lmk084_x  \
0   -0.186653 -0.192817 -0.093502 -0.130788 -0.092936 -0.049739 -0.074582
1   -0.185959 -0.192983 -0.095933 -0.131266 -0.092545 -0.048629 -0.068686
2   -0.187384 -0.194790 -0.097102 -0.133296 -0.094467 -0.050151 -0.071608
3   -0.185740 -0.192620 -0.095362 -0.131958 -0.093649 -0.049781 -0.071049
4   -0.186156 -0.193512 -0.096206 -0.132301 -0.093755 -0.049688 -0.070834
..        ...       ...       ...       ...       ...       ...       ...
639 -0.179471 -0.184245 -0.082554 -0.125276 -0.089413 -0.048088 -0.073967
640 -0.179981 -0.185718 -0.083328 -0.126405 -0.090084 -0.048377 -0.073891
641 -0.180022 -0.185819 -0.084470 -0.126456 -0.090195 -0.048520 -0.074900
642 -0.184973 -0.191041 -0.083043 -0.130470 -0.093148 -0.050410 -0.076904
643 -0.184704 -0.190401 -0.083867 -0.129859 -0.092691 -0.050036 -0.076356

     lmk085_x  lmk086_x  lmk087_x  lmk088_x  lmk089_x  lmk090_x  lmk091_x  \
0   -0.067723 -0.063556 -0.059346 -0.055524 -0.141750 -0.148299 -0.158656
1   -0.063932 -0.060652 -0.056976 -0.052880 -0.139761 -0.146659 -0.157161
2   -0.065382 -0.061755 -0.058100 -0.054160 -0.141324 -0.148155 -0.158729
3   -0.065135 -0.061496 -0.057648 -0.053528 -0.139856 -0.146841 -0.157577
4   -0.064902 -0.061337 -0.057601 -0.053598 -0.140375 -0.147224 -0.157770
..        ...       ...       ...       ...       ...       ...       ...
639 -0.068325 -0.064035 -0.058498 -0.052887 -0.134915 -0.142426 -0.153784
640 -0.067606 -0.063347 -0.058102 -0.052744 -0.135631 -0.142884 -0.153767
641 -0.068066 -0.063698 -0.058428 -0.053124 -0.135874 -0.143081 -0.153922
642 -0.069824 -0.065415 -0.060245 -0.054999 -0.139758 -0.146953 -0.157802
643 -0.069560 -0.065335 -0.060321 -0.055169 -0.139385 -0.146584 -0.157550

     lmk092_x  lmk093_x  lmk094_x  lmk095_x  lmk096_x  lmk097_x  lmk098_x  \
0   -0.168923 -0.214052 -0.582904  0.002224 -0.166293 -0.175399 -0.064324
1   -0.167115 -0.212640 -0.569586  0.002960 -0.165068 -0.174322 -0.064468
2   -0.168674 -0.215583 -0.579708  0.001263 -0.166711 -0.175724 -0.066177
3   -0.167479 -0.213686 -0.572717  0.002317 -0.164891 -0.174020 -0.064711
4   -0.167702 -0.214398 -0.573317  0.001993 -0.165544 -0.174562 -0.065247
..        ...       ...       ...       ...       ...       ...       ...
639 -0.164257 -0.201369 -0.514129  0.010015 -0.158163 -0.167701 -0.054532
640 -0.164070 -0.202782 -0.518013  0.009656 -0.159261 -0.168477 -0.055255
641 -0.164243 -0.203407 -0.522294  0.008558 -0.159434 -0.168621 -0.055950
642 -0.168085 -0.206101 -0.524433  0.010414 -0.164063 -0.173363 -0.055405
643 -0.167898 -0.205952 -0.529154  0.010470 -0.163604 -0.172984 -0.056286

     lmk099_x  lmk100_x  lmk101_x  lmk102_x  lmk103_x  lmk104_x  lmk105_x  \
0   -0.146219 -0.072762 -0.210439 -0.291081 -0.174273 -0.424460 -0.395383
1   -0.147599 -0.073004 -0.206609 -0.285136 -0.176583 -0.415092 -0.383079
2   -0.149967 -0.074709 -0.211969 -0.290874 -0.179111 -0.424161 -0.391327
3   -0.147803 -0.073113 -0.208534 -0.287310 -0.176805 -0.418960 -0.386751
4   -0.148520 -0.073769 -0.209810 -0.288579 -0.177660 -0.421268 -0.389476
..        ...       ...       ...       ...       ...       ...       ...
639 -0.131995 -0.062191 -0.174826 -0.254347 -0.156033 -0.345246 -0.322164
640 -0.133323 -0.063004 -0.176503 -0.256188 -0.157446 -0.347472 -0.324314
641 -0.134122 -0.063828 -0.178437 -0.258231 -0.158396 -0.350543 -0.326789
642 -0.134548 -0.063103 -0.177760 -0.258212 -0.158216 -0.347778 -0.324229
643 -0.135810 -0.064093 -0.179327 -0.259469 -0.159531 -0.353872 -0.328336

     lmk106_x  lmk107_x  lmk108_x  lmk109_x  lmk110_x  lmk111_x  lmk112_x  \
0   -0.362203 -0.196724 -0.135030 -0.147705 -0.163935 -0.365878 -0.480645
1   -0.348531 -0.191599 -0.126422 -0.142130 -0.160960 -0.355240 -0.470391
2   -0.355243 -0.194219 -0.131691 -0.146972 -0.165916 -0.360190 -0.476901
3   -0.350752 -0.192730 -0.127897 -0.142722 -0.161015 -0.354192 -0.471656
4   -0.353754 -0.193106 -0.130099 -0.144811 -0.163188 -0.356831 -0.473097
..        ...       ...       ...       ...       ...       ...       ...
639 -0.295070 -0.189271 -0.077628 -0.083501 -0.092509 -0.308114 -0.423309
640 -0.297160 -0.189669 -0.078735 -0.084744 -0.094103 -0.310609 -0.425577
641 -0.299368 -0.190484 -0.080990 -0.087233 -0.096877 -0.313701 -0.428669
642 -0.296855 -0.193923 -0.078345 -0.084245 -0.093487 -0.312261 -0.428038
643 -0.299607 -0.193395 -0.081011 -0.088490 -0.099221 -0.315079 -0.431319

     lmk113_x  lmk114_x  lmk115_x  lmk116_x  lmk117_x  lmk118_x  lmk119_x  \
0   -0.156814 -0.430796 -0.121905 -0.127175 -0.533763 -0.444884 -0.379662
1   -0.149566 -0.418504 -0.117924 -0.129633 -0.523570 -0.435789 -0.371657
2   -0.155045 -0.423735 -0.122340 -0.131015 -0.530579 -0.441943 -0.377759
3   -0.150058 -0.417450 -0.118792 -0.129190 -0.525267 -0.437090 -0.373416
4   -0.152172 -0.420040 -0.120248 -0.130164 -0.526552 -0.438586 -0.374952
..        ...       ...       ...       ...       ...       ...       ...
639 -0.106460 -0.364417 -0.084472 -0.113397 -0.475502 -0.393639 -0.334238
640 -0.108596 -0.366925 -0.085749 -0.114237 -0.477998 -0.395798 -0.336235
641 -0.111599 -0.370203 -0.088075 -0.115379 -0.481207 -0.398590 -0.338696
642 -0.109153 -0.368194 -0.086158 -0.113946 -0.481245 -0.398117 -0.338200
643 -0.111498 -0.372103 -0.088027 -0.114843 -0.484808 -0.400843 -0.340216

     lmk120_x  lmk121_x  lmk122_x  lmk123_x  lmk124_x  lmk125_x  lmk126_x  \
0   -0.284881 -0.214954 -0.161614 -0.052749 -0.524404 -0.473023 -0.021302
1   -0.278139 -0.209413 -0.156530 -0.049222 -0.515716 -0.461303 -0.021235
2   -0.284015 -0.215057 -0.161750 -0.052741 -0.522963 -0.467247 -0.022279
3   -0.279915 -0.211046 -0.157752 -0.049467 -0.518022 -0.461194 -0.021212
4   -0.281461 -0.212626 -0.159369 -0.050658 -0.519091 -0.463439 -0.021744
..        ...       ...       ...       ...       ...       ...       ...
639 -0.242077 -0.173286 -0.120347 -0.013586 -0.475250 -0.405187 -0.013749
640 -0.244007 -0.175088 -0.121965 -0.014456 -0.478149 -0.407648 -0.014059
641 -0.246255 -0.177331 -0.124348 -0.017000 -0.481000 -0.410965 -0.015276
642 -0.245565 -0.176239 -0.122716 -0.014323 -0.482601 -0.409041 -0.013257
643 -0.247330 -0.178217 -0.124874 -0.016271 -0.484885 -0.413183 -0.013316

     lmk127_x  lmk128_x  lmk129_x  lmk130_x  lmk131_x  lmk132_x  lmk133_x  \
0   -0.151210 -0.592314 -0.121885 -0.179859 -0.404090 -0.130814 -0.568709
1   -0.150186 -0.578223 -0.116856 -0.181377 -0.391727 -0.133098 -0.554954
2   -0.154480 -0.590783 -0.121851 -0.184723 -0.396889 -0.135132 -0.563894
3   -0.151490 -0.583923 -0.117863 -0.182202 -0.390252 -0.133075 -0.557241
4   -0.152639 -0.584946 -0.119471 -0.183108 -0.393224 -0.134121 -0.557641
..        ...       ...       ...       ...       ...       ...       ...
639 -0.122305 -0.514219 -0.080101 -0.160437 -0.340360 -0.113379 -0.505900
640 -0.123647 -0.517294 -0.081592 -0.162057 -0.342965 -0.114321 -0.509963
641 -0.125362 -0.521564 -0.084156 -0.163050 -0.346403 -0.115525 -0.513943
642 -0.124386 -0.521591 -0.082048 -0.163174 -0.344495 -0.114126 -0.517520
643 -0.125899 -0.527369 -0.084165 -0.164410 -0.348003 -0.115205 -0.521570

     lmk134_x  lmk135_x  lmk136_x  lmk137_x  lmk138_x  lmk139_x  lmk140_x  \
0   -0.157482 -0.087822 -0.422887 -0.423478 -0.576451 -0.482790 -0.548106
1   -0.149731 -0.088098 -0.411450 -0.409168 -0.565792 -0.472292 -0.535884
2   -0.155077 -0.089839 -0.416553 -0.415172 -0.574123 -0.479295 -0.546157
3   -0.149871 -0.088011 -0.412543 -0.410546 -0.568483 -0.474911 -0.540224
4   -0.152088 -0.089023 -0.413373 -0.411345 -0.569192 -0.475392 -0.541866
..        ...       ...       ...       ...       ...       ...       ...
639 -0.104796 -0.069540 -0.391415 -0.387730 -0.517967 -0.445043 -0.474951
640 -0.106983 -0.070072 -0.394687 -0.391219 -0.521182 -0.448842 -0.477477
641 -0.110279 -0.071583 -0.397328 -0.394514 -0.524679 -0.451869 -0.481021
642 -0.107513 -0.069340 -0.402386 -0.399585 -0.526784 -0.457259 -0.479714
643 -0.109955 -0.070113 -0.402879 -0.400943 -0.530253 -0.458331 -0.484850

     lmk141_x  lmk142_x  lmk143_x  lmk144_x  lmk145_x  lmk146_x  lmk147_x  \
0   -0.215869 -0.017769 -0.196927 -0.527614 -0.322608 -0.279065 -0.198998
1   -0.204149 -0.017169 -0.194930 -0.516548 -0.312480 -0.269957 -0.198298
2   -0.207154 -0.018557 -0.199549 -0.523864 -0.316853 -0.274518 -0.199913
3   -0.205167 -0.017358 -0.196584 -0.518183 -0.310816 -0.268815 -0.198283
4   -0.205843 -0.017796 -0.197670 -0.519584 -0.313684 -0.271414 -0.198701
..        ...       ...       ...       ...       ...       ...       ...
639 -0.207188 -0.009265 -0.168392 -0.461613 -0.265499 -0.224100 -0.192121
640 -0.208603 -0.009718 -0.169981 -0.463882 -0.267993 -0.226523 -0.192583
641 -0.210768 -0.010815 -0.171541 -0.467309 -0.270872 -0.229315 -0.192584
642 -0.213265 -0.009046 -0.171276 -0.466500 -0.269433 -0.227845 -0.197554
643 -0.212741 -0.009272 -0.172627 -0.470820 -0.272159 -0.230552 -0.197316

     lmk148_x  lmk149_x  lmk150_x  lmk151_x  lmk152_x  lmk153_x  lmk154_x  \
0   -0.514795 -0.123454 -0.281417 -0.348216 -0.007310 -0.013644 -0.236277
1   -0.506638 -0.111024 -0.267025 -0.333974 -0.004789 -0.003241 -0.227680
2   -0.514400 -0.115479 -0.270642 -0.338168 -0.008163 -0.009455 -0.232730
3   -0.509676 -0.114289 -0.267299 -0.334184 -0.003935 -0.009352 -0.227307
4   -0.510460 -0.114682 -0.268354 -0.335206 -0.005546 -0.009118 -0.229697
..        ...       ...       ...       ...       ...       ...       ...
639 -0.471152 -0.122102 -0.261672 -0.320514  0.055605 -0.020938 -0.182632
640 -0.474570 -0.123237 -0.263904 -0.323260  0.054398 -0.021800 -0.184984
641 -0.477274 -0.125283 -0.266458 -0.326158  0.051771 -0.023507 -0.187828
642 -0.480791 -0.127830 -0.269916 -0.330435  0.054813 -0.026202 -0.186030
643 -0.482334 -0.127132 -0.270428 -0.331488  0.050492 -0.025060 -0.188613

     lmk155_x  lmk156_x  lmk157_x  lmk158_x  lmk159_x  lmk160_x  lmk161_x  \
0   -0.196543 -0.170644 -0.509006 -0.201453 -0.244827 -0.287614 -0.331292
1   -0.188191 -0.162762 -0.497231 -0.192756 -0.235954 -0.277648 -0.319973
2   -0.193535 -0.168296 -0.504476 -0.197253 -0.239958 -0.280643 -0.322246
3   -0.188272 -0.163140 -0.498548 -0.191751 -0.234288 -0.274605 -0.315695

In [11]:
framewise_disp

,frame,time,lmk001,lmk002,lmk003,lmk004,lmk005,lmk006,lmk007,lmk008,lmk009,lmk010,lmk011,lmk012,lmk013,lmk014,lmk015,lmk016,lmk017,lmk018,lmk019,lmk020,lmk021,lmk022,lmk023,lmk024,lmk025,lmk026,lmk027,lmk028,lmk029,lmk030,lmk031,lmk032,lmk033,lmk034,lmk035,lmk036,lmk037,lmk038,lmk039,lmk040,lmk041,lmk042,lmk043,lmk044,lmk045,lmk046,lmk047,lmk048,lmk049,lmk050,lmk051,lmk052,lmk053,lmk054,lmk055,lmk056,lmk057,lmk058,lmk059,lmk060,lmk061,lmk062,lmk063,lmk064,lmk065,lmk066,lmk067,lmk068,lmk069,lmk070,lmk071,lmk072,lmk073,lmk074,lmk075,lmk076,lmk077,lmk078,lmk079,lmk080,lmk081,lmk082,lmk083,lmk084,lmk085,lmk086,lmk087,lmk088,lmk089,lmk090,lmk091,lmk092,lmk093,lmk094,lmk095,lmk096,lmk097,lmk098,lmk099,lmk100,lmk101,lmk102,lmk103,lmk104,lmk105,lmk106,lmk107,lmk108,lmk109,lmk110,lmk111,lmk112,lmk113,lmk114,lmk115,lmk116,lmk117,lmk118,lmk119,lmk120,lmk121,lmk122,lmk123,lmk124,lmk125,lmk126,lmk127,lmk128,lmk129,lmk130,lmk131,lmk132,lmk133,lmk134,lmk135,lmk136,lmk137,lmk138,lmk139,lmk140,lmk141,lmk142,lmk143,lmk144,lmk145,lmk146,lmk147,lmk148,lmk149,lmk150,lmk151,lmk152,lmk153,lmk154,lmk155,lmk156,lmk157,lmk158,lmk159,lmk160,lmk161,lmk162,lmk163,lmk164,lmk165,lmk166,lmk167,lmk168,lmk169,lmk170,lmk171,lmk172,lmk173,lmk174,lmk175,lmk176,lmk177,lmk178,lmk179,lmk180,lmk181,lmk182,lmk183,lmk184,lmk185,lmk186,lmk187,lmk188,lmk189,lmk190,lmk191,lmk192,lmk193,lmk194,lmk195,lmk196,lmk197,lmk198,lmk199,lmk200,lmk201,lmk202,lmk203,lmk204,lmk205,lmk206,lmk207,lmk208,lmk209,lmk210,lmk211,lmk212,lmk213,lmk214,lmk215,lmk216,lmk217,lmk218,lmk219,lmk220,lmk221,lmk222,lmk223,lmk224,lmk225,lmk226,lmk227,lmk228,lmk229,lmk230,lmk231,lmk232,lmk233,lmk234,lmk235,lmk236,lmk237,lmk238,lmk239,lmk240,lmk241,lmk242,lmk243,lmk244,lmk245,lmk246,lmk247,lmk248,lmk249,lmk250,lmk251,lmk252,lmk253,lmk254,lmk255,lmk256,lmk257,lmk258,lmk259,lmk260,lmk261,lmk262,lmk263,lmk264,lmk265,lmk266,lmk267,lmk268,lmk269,lmk270,lmk271,lmk272,lmk273,lmk274,lmk275,lmk276,lmk277,lmk278,lmk279,lmk280,lmk281,lmk282,lmk283,lmk284,lmk285,lmk286,lmk287,lmk288,lmk289,lmk290,lmk291,lmk292,lmk293,lmk294,lmk295,lmk296,lmk297,lmk298,lmk299,lmk300,lmk301,lmk302,lmk303,lmk304,lmk305,lmk306,lmk307,lmk308,lmk309,lmk310,lmk311,lmk312,lmk313,lmk314,lmk315,lmk316,lmk317,lmk318,lmk319,lmk320,lmk321,lmk322,lmk323,lmk324,lmk325,lmk326,lmk327,lmk328,lmk329,lmk330,lmk331,lmk332,lmk333,lmk334,lmk335,lmk336,lmk337,lmk338,lmk339,lmk340,lmk341,lmk342,lmk343,lmk344,lmk345,lmk346,lmk347,lmk348,lmk349,lmk350,lmk351,lmk352,lmk353,lmk354,lmk355,lmk356,lmk357,lmk358,lmk359,lmk360,lmk361,lmk362,lmk363,lmk364,lmk365,lmk366,lmk367,lmk368,lmk369,lmk370,lmk371,lmk372,lmk373,lmk374,lmk375,lmk376,lmk377,lmk378,lmk379,lmk380,lmk381,lmk382,lmk383,lmk384,lmk385,lmk386,lmk387,lmk388,lmk389,lmk390,lmk391,lmk392,lmk393,lmk394,lmk395,lmk396,lmk397,lmk398,lmk399,lmk400,lmk401,lmk402,lmk403,lmk404,lmk405,lmk406,lmk407,lmk408,lmk409,lmk410,lmk411,lmk412,lmk413,lmk414,lmk415,lmk416,lmk417,lmk418,lmk419,lmk420,lmk421,lmk422,lmk423,lmk424,lmk425,lmk426,lmk427,lmk428,lmk429,lmk430,lmk431,lmk432,lmk433,lmk434,lmk435,lmk436,lmk437,lmk438,lmk439,lmk440,lmk441,lmk442,lmk443,lmk444,lmk445,lmk446,lmk447,lmk448,lmk449,lmk450,lmk451,lmk452,lmk453,lmk454,lmk455,lmk456,lmk457,lmk458,lmk459,lmk460,lmk461,lmk462,lmk463,lmk464,lmk465,lmk466,lmk467,lmk468,overall,lower_face,upper_face,lips,eyebrows,mouth_openness
0,0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.137022
1,1,0.033333,-0.000522,0.023118,0.015908,0.020357,0.023935,0.022480,0.018437,0.019423,0.010793,0.012743,0.055492,0.001399,0.003308,0.003847,0.011466,0.013567,0.016130,0.019298,0.021099,0.022759,0.021007,0.030531,0.014251,0.015157,0.016573,0.018525,0.014259,0.010358,0.009757,0.012436,0.015314,0.017488,0.021601,0.019096,0.019313,0.017241,0.013308,0.002359,0.002207,0.003337,0.003806,0.002577,0.003832,0.011575,0.023692,0.023729,0.014829,0.016120,0.021896,0.020848,0.011174,0.022466,0.014960,0.014837,0.036274,0.011930,0.010533,0.008310,0.018597,0.021326,0.018612,0.007990,0.008144,0.016011,0.020009,0.015132,0.014730,0.048010,0.027214,0.030649,0.015750,0.024002,0.000438,0.002028,0.003777,0.019965,0.007686,0.009485,0.008186,0.023723,0.003568,2.829263e-03,0.002726,0.020590,0.018924,0.015693,0.012252,0.010879,0.008692,0.009178,0.011253,0.012590,0.007500,0.014307,0.020991,0.008666,0.008951,0.016181,0.017593,0.017383,0.015493,0.014226,0.019575,0.041478,0.029047,0.015860,0.014166,0.012674,0.035384,0.053240,0.017747,0.016812,0.014192,0.017223,0.016696,0.023515,0.015824,0.016002,0.015011,0.014767,0.014834,0.015515,0.017134,0.011898,0.016050,0.022236,0.017255,0.019977,0.015591,0.017859,0.018168,0.022282,0.015508,0.014136,0.021913,0.019337,0.023659,0.012081,0.017005,0.022333,0.024123,0.020762,0.015447,0.017056,0.017806,0.016183,0.010105,0.009481,0.026536,0.026059,0.024950,0.037984,0.025935,0.015759,0.015279,0.014729,0.016703,0.015687,0.015386,0.016211,0.017239,0.018109,0.026220,0.018986,0.009778,0.010467,0.022113,0.010604,0.014137,0.021265,0.022523,0.024959,0.021600,0.014933,0.018347,0.025328,0.026385,0.012186,0.009515,0.011148,0.013827,0.016646,0.017120,0.005550,0.005968,0.005683,0.006305,0.007948,0.017058,0.011289,0.012698,0.005818,0.011968,0.011865,0.019327,0.020769,0.018849,0.019691,0.019044,0.023928,0.022561,0.021954,0.013584,0.013930,0.016989,0.009493,0.009400,0.007596,0.023880,0.018481,0.017211,0.019668,0.010117,0.011089,0.013126,0.014527,0.006749,0.017915,0.024118,0.022515,0.023827,0.008705,0.010638,0.011811,0.013290,0.015398,0.018283,0.015343,0.016891,0.015839,0.014627,0.014400,0.014341,0.014414,0.015831,0.020870,0.019733,0.023817,0.022419,0.023453,0.018613,0.022123,0.020818,0.013465,0.013982,0.014834,0.019200,0.017123,0.020353,0.019455,0.021270,0.031718,0.015988,0.016089,0.016543,0.018517,0.016256,0.012935,0.012378,0.014837,0.016348,0.017912,0.023844,0.019715,0.018581,0.018193,0.012694,0.001432,0.003153,0.003836,0.006647,0.005342,0.007762,0.014739,0.023456,0.023355,0.018932,0.016961,0.020634,0.019880,0.012192,0.022414,0.013757,0.017584,0.038069,0.009815,0.013306,0.011797,0.018745,0.019769,0.016994,0.012826,0.013153,0.019953,0.019086,0.011350,0.013185,0.050282,0.029277,0.033270,0.020665,0.026555,0.001664,0.004445,0.007190,0.018093,0.012824,0.013261,0.013065,0.023279,0.007494,0.005822,0.004189,0.021903,0.019408,0.016541,0.013177,0.011490,0.012289,0.012108,0.013998,0.015379,0.006845,0.014341,0.012498,0.013094,0.015018,0.015848,0.016385,0.016015,0.013517,0.018403,0.044016,0.031621,0.016379,0.016667,0.012277,0.036923,0.054528,0.017583,0.017260,0.016087,0.019576,0.017163,0.022252,0.016261,0.015141,0.014500,0.014256,0.015683,0.016422,0.017982,0.013662,0.018335,0.022618,0.017619,0.017598,0.016952,0.017066,0.019605,0.021479,0.014957,0.016080,0.021630,0.019574,0.022736,0.014524,0.018216,0.023055,0.025053,0.020932,0.015878,0.018396,0.018005,0.017107,0.013849,0.013268,0.026186,0.025591,0.024250,0.017274,0.017126,0.016583,0.019662,0.017337,0.018063,0.018289,0.018280,0.018720,0.024912,0.018845,0.009130,0.021051,0.009374,0.021766,0.023162,0.025558,0.021759,0.016774,0.018131,0.026032,0.014243,0.011305,0.012871,0.015703,0.018016,0.019014,0.010472,0.009903,0.009841,0.008276,0.012565,0.017523,0.013626,0.015016,0.009907,0.014345,0.012888,0.021170,0.018966,0.019273,0.023399,0.016472,0.012935,0.019174,0.010281,0.008960,0.010350,0.024922,0.018781,0.018064,0.021308,0.013150,0.013813,0.014437,0.016251,0.008228,0.018189,0.023475,0.020527,0.023123,0.009538,0.010452,0.012455,0.015607,0.018511,0.018709,0.015779,0.016543,0.015017,0.014698,0.015224,0.015901,0.016224,0.014974,0.019252,0.019552,0.023711,0.022940,0.023823,0.017205,0.022753,0.021505,0.015822,0.015776,0.016613,0.019185,0.018637,0.016821,0.013378,0.018802,0.009009,0.015412,0.185313
2,2,0.066667,-0.000522,0.003968,0.001483,0.004244,0.004332,0.004474,0.006794,0.013152,0.010158,0.014919,0.008536,-0.000227,-0.000133,0.000572,0.000820,0.000541,0.000692,0.001300,0.004193,0.003150,0.001755,0.015837,0.012406,0.012234,0.011461,0.012262,0.011895,0.005608,0.005782,0.005424,0.006572,0.011616,0.007211,0.013674,0.016734,0.010411,0.008029,0.000945,0.000980,0.002331,0.003121,0.002309,0.003164,0.005710,0.003335,0.003593,0.009263,0.008653,0.003052,0.004347,0.009781,0.003538,0.016365,0.012548,0.012323,0.013903,0.007514,0.006552,0.022981,0.002859,0.002992,0.005235,0.004949,0.014767,0.004026,0.017843,0.019418,0.009274,0.011175,0.012470,0.011057,0.012025,0.000572,0.002132,0.002885,0.003136,0.004933,0.004138,0.004957,0.001488,0.003510,2.551634e-03,0.001795,0.004380,0.001439,0.001035,0.001184,0.001648,0.003393,0.003349,0.003500,0.003888,0.005292,0.023454,0.001948,0.004390,0.003995,0.002467,0.004712,0.002849,0.009006,0.008527,0.005231,0.010090,0.012259,0.017736,0.005343,0.017542,0.009831,0.008756,0.011725,0.012125,0.011432,0.007510,0.008145,0.001668,0.013611,0.011195,0.010314,0.009895,0.010537,0.009826,0.006485,0.014070,0.007832,0.002646,0.007455,0.021095,0.009162,0.006771,0.011345,0.002803,0.023758,0.012119,0.002798,0.014766,0.017122,0.019045,0.017827,0.014083,0.007680,0.001499,0.008033,0.012228,0.012549,0.012537,0.004632,0.015434,0.007862,0.011012,0.013344,0.008880,0.007894,0.012748,0.012755,0.012212,0.009868,0.017777,0.020758,0.021247,0.019469,0.017181,0.018952,0.012925,0.001805,0.004534,0.002306,0.002603,0.004743,0.011719,0.009578,0.006354,0.020506,0.014221,0.005963,0.006595,0.009019,0.020215,0.002434,0.002075,0.002559,0.002861,0.004676,0.003757,0.003707,0.003972,0.005421,0.012029,0.007143,0.006473,0.008986,0.004016,0.014487,0.004456,0.006630,0.004955,0.005696,0.006286,0.005063,0.005891,0.005475,0.005606,0.007572,0.006970,0.006951,0.008400,0.007071,0.010045,0.005867,0.006168,0.009573,0.008396,0.008087,0.016276,0.010810,0.020174,0.007076,0.006687,0.001228,0.002415,0.002716,0.006537,0.008465,0.008255,0.006268,0.005031,0.010448,0.018030,0.011709,0.010791,0.011130,0.011657,0.011042,0.010423,0.022725,0.003124,0.004243,0.002149,0.002205,0.001758,0.003918,0.002504,0.001664,0.010349,0.009042,0.007774,0.015275,0.008614,0.005681,0.022059,0.003375,0.009063,0.017550,0.018044,0.017667,0.020049,0.016503,0.011330,0.010668,0.012927,0.015242,0.015898,0.009005,0.023503,0.014135,0.013376,0.008054,0.000305,-0.000220,0.001197,0.001322,0.000327,0.000653,0.003973,0.004281,0.004990,0.008327,0.010537,0.005482,0.006195,0.009876,0.004914,0.011281,0.010045,0.006322,0.010873,0.010993,0.003871,0.021199,0.004834,0.004241,0.001663,0.001761,0.010229,0.005276,0.012723,0.014506,0.006670,0.006422,0.009419,0.007134,0.006588,0.000088,0.000689,0.001105,0.004906,0.001591,0.001499,0.002024,0.004898,0.000690,0.000272,-0.000017,0.004389,0.001577,0.000928,0.000723,0.000863,0.001409,0.001355,0.001254,0.001610,0.003410,0.020604,0.001896,0.001658,0.002939,0.004532,0.003762,0.010349,0.010088,0.005973,0.005470,0.007671,0.011973,0.004093,0.014587,0.008741,0.007616,0.018566,0.013729,0.015574,0.014027,0.010059,0.005466,0.014451,0.012712,0.011319,0.011869,0.012451,0.012365,0.007845,0.013570,0.010278,0.003561,0.008413,0.015261,0.011342,0.006112,0.019657,0.005599,0.021676,0.016595,0.005389,0.013994,0.016952,0.017415,0.016263,0.010477,0.010304,0.002226,0.008248,0.013080,0.019889,0.019459,0.001745,0.013662,0.009355,0.013428,0.015074,0.018821,0.017758,0.016808,0.008806,0.023610,0.028113,0.030050,0.029787,0.027574,0.011852,0.020798,0.003131,0.005213,0.002324,0.013110,0.011928,0.008221,0.019440,0.019113,0.007649,0.011255,0.018070,0.001066,0.001141,0.001166,0.001718,0.004225,0.001302,0.001534,0.001652,0.003085,0.010601,0.008948,0.007963,0.012663,0.001186,0.012515,0.004774,0.007276,0.006992,0.006660,0.006305,0.007502,0.006266,0.007484,0.008132,0.006174,0.008291,0.007314,0.006879,0.010720,0.009955,0.007028,0.014161,0.010331,0.018197,0.005528,0.008145,0.005258,0.005367,0.005517,0.004151,0.005657,0.007200,0.009168,0.011647,0.015983,0.016442,0.015727,0.014400,0.014868,0.014912,0.014453,0.013205,0.018356,0.005152,0.006096,0.004773,0.003999,0.004579,0.004643,0.003855,0.002807,0.014147,0.011360,0.009607,0.025483,0.017046,0.008674,0.006135,0.010114,0.001901,0.011854,0.185008
3,3,0.100000,-0.000522,0.001123,0.000881,0.003009,0.001461,0.002091,0.004422,0.007117,0.010354,0.012708,0.012347,-0.000282,-0.000302,-0.000381,0.001129,0.001376,0.001622,0.001436,0.000239,0.000996,0.001632,0.010887,0.005772,0.006045,0.006632,0.007214,0.005760,0.007562,0.007383,0.007742,0.007800,0.007196,0.003593,0.007135,0.009021,0.008490,0.004024,0.000188,0.000108,0.000900,0.001413,0.000641,0.001129,0.002191,0.001549,0.001905,0.010837,0.004341,0.002851,0.003114,0.005490,0.002425,0.012273,0.011544,0.011765,0.011745,0.007012,0.002624,0.006651,0.002367,0.001876,0.001907,0.001917,0.012344,0.002804,0.012915,0.013803,0.012723,0.011753,0.012517,0.011382,0.011034,0.000184,0.000755,0.001214,0.002347,0.001849,0.001587,0.002004,0.002224,0.001201,6.788035e-04,0.000164,0.000678,0.001413,0.001511,0.001300,0.001109,0.001375,0.001310,0.001207,0.001271,0.002342,0.008413,0.000996,0.001671,0.001618,0.001507,0.002629,0.001775,0.004418,0.004885,0.003047,0.012307,0.012307,0.013012,0.001887,0.013449,0.011744,0.012601,0.007074,0.007301,0.005799,0.008580,0.004418,0.002677,0.007662,0.006660,0.005946,0.005243,0.004912,0.004819,0.004596,0.006864,0.009728,0.001262,0.003728,0.009916,0.004907,0.003152,0.007576,0.002907,0.007604,0.005907,0.002727,0.005093,0.005741,0.007371,0.005348,0.009935,0.004708,0.001195,0.003819,0.008822,0.006782,0.006274,0.001663,0.006216,0.004662,0.005793,0.005763,0.011108,0.003454,0.005906,0.005887,0.005901,0.010235,0.005356,0.005142,0.005394,0.005992,0.006382,0.010470,0.007078,0.000412,0.002091,0.002329,0.001001,0.006998,0.005147,0.005093,0.003712,0.005954,0.005655,0.003704,0.002893,0.005428,0.006530,0.001177,0.001134,0.001185,0.001092,0.001491,0.001628,0.001642,0.001778,0.002573,0.005368,0.004552,0.006964,0.006476,0.001712,0.005150,0.007220,0.002308,0.002794,0.003642,0.003407,0.003222,0.001831,0.000676,0.001389,0.003086,0.003298,0.002878,0.004360,0.003454,0.004468,0.002625,0.003319,0.004355,0.004039,0.003543,0.005740,0.004448,0.005898,0.003583,0.003739,0.002390,0.002616,0.002477,0.008953,0.009556,0.009562,0.009398,0.009130,0.007976,0.008291,0.006814,0.006304,0.005650,0.005372,0.005351,0.005398,0.009132,0.002610,0.003192,0.001944,0.001704,0.001996,0.002471,0.001439,0.001309,0.006031,0.005708,0.005379,0.006687,0.007877,0.002418,0.006165,0.001036,0.012798,0.005160,0.005268,0.005522,0.006402,0.004888,0.006922,0.006867,0.006826,0.006635,0.007020,0.000789,0.006200,0.011106,0.008491,0.003371,0.000121,0.000007,0.001151,0.002003,0.000908,0.001690,0.002809,0.000692,0.001040,0.009608,0.003738,0.001768,0.002085,0.005084,0.001757,0.011380,0.010103,0.012852,0.011658,0.006704,0.003572,0.008978,0.001677,0.001010,0.003408,0.003049,0.011528,0.001736,0.012470,0.013245,0.012814,0.011848,0.012326,0.010763,0.011671,0.000085,0.001025,0.001728,0.001369,0.003218,0.002678,0.002963,0.001119,0.001523,0.000916,0.000103,0.000173,0.001637,0.001701,0.001526,0.001289,0.002099,0.002144,0.002178,0.002214,0.002080,0.011125,0.002574,0.002686,0.000831,0.001661,0.000928,0.003898,0.004041,0.002225,0.012976,0.012301,0.012528,0.001788,0.013308,0.011569,0.012579,0.005989,0.007828,0.005195,0.007637,0.003766,0.001375,0.008688,0.006928,0.005869,0.004779,0.004486,0.004264,0.004257,0.007880,0.008916,0.000776,0.003263,0.012620,0.004397,0.002663,0.006751,0.001839,0.010097,0.005473,0.001695,0.005023,0.005149,0.009893,0.006840,0.011362,0.001367,0.000970,0.003355,0.009459,0.005796,0.005478,0.002863,0.007463,0.002533,0.002252,0.003186,0.005231,0.005306,0.005442,0.010138,0.005192,0.005192,0.005359,0.005582,0.005779,0.012837,0.005991,0.001411,0.001367,0.000315,0.003165,0.001836,0.001596,0.007431,0.005259,0.003191,0.002101,0.009366,0.001683,0.001725,0.002015,0.001877,0.000971,0.002373,0.002584,0.002756,0.002912,0.005488,0.003986,0.006857,0.006031,0.002284,0.005959,0.007074,0.000675,0.003260,0.002572,-0.000291,0.002871,0.002624,0.001662,0.003667,0.002719,0.004257,0.000593,0.002736,0.002949,0.001621,0.003684,0.007186,0.004371,0.008528,0.003213,0.003220,0.001030,0.001449,0.000911,0.008730,0.009054,0.008523,0.007988,0.007634,0.007571,0.010523,0.006477,0.005703,0.005037,0.004924,0.004623,0.004867,0.012010,0.001495,0.002456,0.000732,0.000871,0.000858,0.001493,0.000797,0.000926,0.005534,0.005368,0.004902,0.006032,0.006881,0.004809,0.002629,0.006048,0.001444,0.011078,0.195894

In [12]:
summary

,overall_mean,lower_face_mean,upper_face_mean,lips_mean,eyebrows_mean,mouth_openness_mean,overall_std,lower_face_std,upper_face_std,lips_std,eyebrows_std,mouth_openness_std
0,0.015443,0.014805,0.015817,0.013397,0.02261,0.878355,0.0089,0.010404,0.009567,0.011449,0.01566,0.662627

In [13]:
print('framewise_loc shape:', framewise_loc.shape)
print('framewise_disp shape:', framewise_disp.shape)
print('summary shape:', summary.shape)
summary.head()

framewise_loc shape: (644, 1406)
framewise_disp shape: (644, 476)
summary shape: (1, 12)

,overall_mean,lower_face_mean,upper_face_mean,lips_mean,eyebrows_mean,mouth_openness_mean,overall_std,lower_face_std,upper_face_std,lips_std,eyebrows_std,mouth_openness_std
0,0.015443,0.014805,0.015817,0.013397,0.02261,0.878355,0.0089,0.010404,0.009567,0.011449,0.01566,0.662627

## normalization = False

In [14]:
import openwillis.face as ef

framewise_loc_no, framewise_disp_no, summary_no = ef.facial_expressivity(
	filepath = 'video.mov', 
	baseline_filepath = 'sample_data/baseline.mp4', 
	bbox_list = [], 
	base_bbox_list = [], 
	frames_per_second = 30, 
	normalize = False, 
	align = False, 
	rolling_std_seconds = 3, 
	split_by_speaking = False)

I0000 00:00:1779292805.042164 10644939 gl_context.cc:357] GL version: 2.1 (2.1 Metal - 89.4), renderer: Apple M3 Pro
W0000 00:00:1779292805.043652 11282268 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1779292805.046963 11282270 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

In [15]:
framewise_loc_no

     frame       time  lmk001_x  lmk002_x  lmk003_x  lmk004_x  lmk005_x  \
0        0   0.000000  0.529066  0.530244  0.529082  0.521374  0.530273
1        1   0.033333  0.528162  0.529195  0.528414  0.520622  0.529203
2        2   0.066667  0.529898  0.530699  0.529859  0.521919  0.530705
3        3   0.100000  0.529801  0.530729  0.529972  0.522255  0.530776
4        4   0.133333  0.530461  0.531308  0.530594  0.522732  0.531333
..     ...        ...       ...       ...       ...       ...       ...
639    639  21.300000  0.524936  0.527289  0.526741  0.521608  0.527944
640    640  21.333333  0.524425  0.526752  0.526153  0.521029  0.527409
641    641  21.366667  0.523127  0.525226  0.524653  0.519343  0.525856
642    642  21.400000  0.522179  0.524725  0.523978  0.518919  0.525399
643    643  21.433333  0.523461  0.526064  0.525240  0.520012  0.526710

     lmk006_x  lmk007_x  lmk008_x  lmk009_x  lmk010_x  lmk011_x  lmk012_x  \
0    0.529809  0.528281  0.461595  0.527727  0.527745  0.527467  0.528978
1    0.528920  0.527926  0.462472  0.527608  0.527640  0.526832  0.528117
2    0.530343  0.529031  0.463205  0.528680  0.528754  0.527898  0.529839
3    0.530517  0.529501  0.464553  0.529266  0.529379  0.528690  0.529709
4    0.531051  0.529980  0.464580  0.529717  0.529812  0.528988  0.530380
..        ...       ...       ...       ...       ...       ...       ...
639  0.528965  0.531453  0.465708  0.533418  0.534420  0.536739  0.524543
640  0.528390  0.530763  0.465015  0.532695  0.533702  0.535851  0.524053
641  0.526779  0.529006  0.462927  0.530885  0.531893  0.534079  0.522759
642  0.526344  0.528556  0.462586  0.530440  0.531453  0.533702  0.521775
643  0.527572  0.529531  0.462868  0.531217  0.532136  0.534073  0.523074

     lmk013_x  lmk014_x  lmk015_x  lmk016_x  lmk017_x  lmk018_x  lmk019_x  \
0    0.528763  0.528505  0.528252  0.528343  0.528320  0.528126  0.527632
1    0.528006  0.527906  0.527890  0.527950  0.527984  0.528021  0.527896
2    0.529681  0.529494  0.529421  0.529501  0.529507  0.529456  0.529057
3    0.529562  0.529418  0.529405  0.529444  0.529426  0.529371  0.529019
4    0.530243  0.530097  0.530072  0.530135  0.530128  0.530079  0.529727
..        ...       ...       ...       ...       ...       ...       ...
639  0.524386  0.524442  0.524447  0.524183  0.523860  0.523596  0.523262
640  0.523903  0.523939  0.523983  0.523746  0.523433  0.523161  0.522752
641  0.522598  0.522608  0.522602  0.522387  0.522072  0.521783  0.521291
642  0.521565  0.521550  0.521461  0.521229  0.520902  0.520581  0.520039
643  0.522844  0.522817  0.522601  0.522396  0.522102  0.521812  0.521311

     lmk020_x  lmk021_x  lmk022_x  lmk023_x  lmk024_x  lmk025_x  lmk026_x  \
0    0.529861  0.520902  0.428965  0.487834  0.478677  0.470071  0.458496
1    0.528945  0.519945  0.429760  0.488137  0.479072  0.470536  0.459321
2    0.530424  0.521401  0.428743  0.488761  0.479682  0.471165  0.459829
3    0.530480  0.521607  0.430171  0.489769  0.480761  0.472330  0.461152
4    0.531069  0.522137  0.430383  0.489997  0.480954  0.472487  0.461255
..        ...       ...       ...       ...       ...       ...       ...
639  0.526927  0.518199  0.435253  0.491376  0.482048  0.473413  0.462410
640  0.526363  0.517612  0.434661  0.490612  0.481320  0.472726  0.461730
641  0.524851  0.516091  0.432453  0.488731  0.479419  0.470790  0.459652
642  0.524305  0.515463  0.432205  0.488214  0.478880  0.470268  0.459276
643  0.525649  0.516559  0.431641  0.488781  0.479361  0.470645  0.459536

     lmk027_x  lmk028_x  lmk029_x  lmk030_x  lmk031_x  lmk032_x  lmk033_x  \
0    0.495631  0.476251  0.485682  0.467310  0.461164  0.451443  0.492507
1    0.495892  0.476715  0.486002  0.468026  0.462096  0.452044  0.493056
2    0.496519  0.477574  0.486773  0.468878  0.462873  0.452390  0.494105
3    0.497477  0.478708  0.487802  0.470130  0.464218  0.453625  0.494456
4    0.497721  0.478785  0.487940  0.470148  0.464208  0.453856  0.495005
..        ...       ...       ...       ...       ...       ...       ...
639  0.499420  0.480849  0.490411  0.471879  0.465708  0.454609  0.487750
640  0.498626  0.480176  0.489674  0.471235  0.465066  0.453997  0.487216
641  0.496729  0.478181  0.487688  0.469212  0.463025  0.451938  0.485456
642  0.496279  0.477872  0.487387  0.468903  0.462710  0.451509  0.484249
643  0.496911  0.478110  0.487786  0.469045  0.462823  0.451674  0.485428

     lmk034_x  lmk035_x  lmk036_x  lmk037_x  lmk038_x  lmk039_x  lmk040_x  \
0    0.458521  0.424436  0.441100  0.482571  0.517757  0.519125  0.505973
1    0.459505  0.425193  0.441770  0.482131  0.516656  0.518190  0.504736
2    0.460230  0.424732  0.442009  0.482812  0.518245  0.519723  0.506167
3    0.461635  0.426112  0.443310  0.483449  0.518247  0.519703  0.506301
4    0.461639  0.426490  0.443583  0.483865  0.518877  0.520368  0.506905
..        ...       ...       ...       ...       ...       ...       ...
639  0.462825  0.428619  0.444924  0.481558  0.513265  0.514513  0.501299
640  0.462141  0.428126  0.444378  0.480951  0.512781  0.514024  0.500833
641  0.459998  0.425900  0.442255  0.479241  0.511450  0.512700  0.499485
642  0.459711  0.425373  0.441868  0.478388  0.510380  0.511459  0.498191
643  0.459942  0.425039  0.441798  0.479162  0.511610  0.512736  0.499333

     lmk041_x  lmk042_x  lmk043_x  lmk044_x  lmk045_x  lmk046_x  lmk047_x  \
0    0.498267  0.510610  0.503739  0.485722  0.522435  0.521197  0.446363
1    0.497016  0.509517  0.502576  0.485215  0.521311  0.520117  0.447284
2    0.498345  0.510899  0.503902  0.486450  0.522861  0.521658  0.447669
3    0.498592  0.510990  0.504112  0.486872  0.522965  0.521800  0.448961
4    0.499165  0.511623  0.504694  0.487369  0.523497  0.522302  0.449089
..        ...       ...       ...       ...       ...       ...       ...
639  0.493682  0.505894  0.499160  0.481321  0.519337  0.518724  0.451457
640  0.493179  0.505384  0.498603  0.480886  0.518802  0.518213  0.450850
641  0.491821  0.504060  0.497268  0.479404  0.517257  0.516651  0.448812
642  0.490293  0.502640  0.495665  0.477835  0.516762  0.516208  0.448570
643  0.491429  0.503867  0.496867  0.478848  0.518025  0.517420  0.448596

     lmk048_x  lmk049_x  lmk050_x  lmk051_x  lmk052_x  lmk053_x  lmk054_x  \
0    0.500513  0.499963  0.499082  0.455440  0.521336  0.466988  0.454860
1    0.500055  0.498292  0.497530  0.455372  0.520372  0.468145  0.455864
2    0.500818  0.499621  0.498739  0.455666  0.521792  0.468563  0.456355
3    0.501474  0.500018  0.499181  0.456563  0.522029  0.469543  0.457525
4    0.501856  0.500487  0.499631  0.456959  0.522514  0.469616  0.457607
..        ...       ...       ...       ...       ...       ...       ...
639  0.501789  0.497243  0.496943  0.454841  0.520127  0.472036  0.460052
640  0.501123  0.496642  0.496336  0.454228  0.519580  0.471418  0.459442
641  0.499366  0.495118  0.494785  0.452352  0.517965  0.469562  0.457472
642  0.498766  0.494382  0.494068  0.451401  0.517537  0.469282  0.457238
643  0.499534  0.495235  0.494895  0.451995  0.518689  0.469694  0.457413

     lmk055_x  lmk056_x  lmk057_x  lmk058_x  lmk059_x  lmk060_x  lmk061_x  \
0    0.437727  0.507513  0.494145  0.478900  0.432353  0.506590  0.514217
1    0.438324  0.508014  0.494364  0.478200  0.433433  0.505010  0.513132
2    0.437650  0.508594  0.495048  0.479394  0.433285  0.506392  0.514497
3    0.438942  0.509250  0.496000  0.479910  0.434655  0.506748  0.514775
4    0.439118  0.509484  0.496200  0.480354  0.435178  0.507239  0.515290
..        ...       ...       ...       ...       ...       ...       ...
639  0.444475  0.512193  0.498864  0.474857  0.433630  0.503727  0.511568
640  0.443876  0.511516  0.498083  0.474317  0.432781  0.503101  0.510953
641  0.441757  0.509763  0.496111  0.472830  0.430527  0.501593  0.509468
642  0.441563  0.509350  0.495799  0.471189  0.429083  0.500814  0.508711
643  0.441082  0.510157  0.496339  0.472154  0.429122  0.501739  0.509693

     lmk062_x  lmk063_x  lmk064_x  lmk065_x  lmk066_x  lmk067_x  lmk068_x  \
0    0.489279  0.493283  0.449454  0.499409  0.484004  0.482229  0.474891
1    0.488072  0.492075  0.450518  0.497795  0.485100  0.483326  0.474757
2    0.489343  0.493386  0.450746  0.499051  0.485471  0.483701  0.475043
3    0.489748  0.493813  0.451912  0.499473  0.486269  0.484499  0.476070
4    0.490276  0.494298  0.452014  0.499960  0.486356  0.484603  0.476263
..        ...       ...       ...       ...       ...       ...       ...
639  0.484727  0.488898  0.455034  0.496635  0.488722  0.487439  0.482280
640  0.484223  0.488323  0.454421  0.496005  0.488098  0.486830  0.481644
641  0.482853  0.486949  0.452468  0.494483  0.486322  0.485050  0.479703
642  0.480969  0.485089  0.452230  0.493656  0.485989  0.484750  0.479541
643  0.482064  0.486218  0.452347  0.494486  0.486637  0.485317  0.479370

     lmk069_x  lmk070_x  lmk071_x  lmk072_x  lmk073_x  lmk074_x  lmk075_x  \
0    0.443563  0.479423  0.440840  0.434919  0.518322  0.508700  0.501149
1    0.444443  0.479930  0.441731  0.435721  0.517289  0.507488  0.499935
2    0.444128  0.480295  0.441831  0.435217  0.518884  0.508916  0.501274
3    0.445301  0.481163  0.443135  0.436540  0.518867  0.509015  0.501487
4    0.445420  0.481320  0.443278  0.436717  0.519517  0.509627  0.502068
..        ...       ...       ...       ...       ...       ...       ...
639  0.449481  0.485715  0.446070  0.440415  0.513681  0.503851  0.496488
640  0.448880  0.485106  0.445467  0.439829  0.513198  0.503372  0.495977
641  0.446886  0.483259  0.443407  0.437716  0.511892  0.502045  0.494638
642  0.446661  0.483022  0.443189  0.437485  0.510715  0.500678  0.493079
643  0.446541  0.483250  0.443137  0.437192  0.511982  0.501880  0.494246

     lmk076_x  lmk077_x  lmk078_x  lmk079_x  lmk080_x  lmk081_x  lmk082_x  \
0    0.508881  0.491435  0.495208  0.494090  0.512105  0.505342  0.512208
1    0.507492  0.490146  0.494241  0.492960  0.510663  0.504218  0.511281
2    0.508850  0.491434  0.495583  0.494227  0.512116  0.505488  0.512598
3    0.509193  0.491841  0.495920  0.494665  0.512406  0.505730  0.512718
4    0.509702  0.492357  0.496474  0.495131  0.512897  0.506307  0.513344
..        ...       ...       ...       ...       ...       ...       ...
639  0.506139  0.486888  0.490752  0.489842  0.509212  0.501074  0.507905
640  0.505514  0.486350  0.490319  0.489232  0.508634  0.500472  0.507354
641  0.504018  0.484989  0.488935  0.487834  0.507084  0.499109  0.505996
642  0.503200  0.483095  0.487186  0.486038  0.506469  0.497497  0.504557
643  0.504112  0.484205  0.488266  0.487181  0.507480  0.498717  0.505799

     lmk083_x  lmk084_x  lmk085_x  lmk086_x  lmk087_x  lmk088_x  lmk089_x  \
0    0.520044  0.515537  0.516781  0.517537  0.518301  0.518994  0.503353
1    0.519292  0.515633  0.516500  0.517099  0.517769  0.518516  0.502668
2    0.520714  0.516784  0.517925  0.518589  0.519258  0.519979  0.504018
3    0.520721  0.516841  0.517920  0.518584  0.519286  0.520037  0.504290
4    0.521390  0.517529  0.518612  0.519263  0.519945  0.520676  0.504833
..        ...       ...       ...       ...       ...       ...       ...
639  0.515777  0.510847  0.511922  0.512739  0.513794  0.514863  0.499238
640  0.515258  0.510423  0.511614  0.512421  0.513415  0.514430  0.498723
641  0.513912  0.508901  0.510199  0.511029  0.512030  0.513037  0.497320
642  0.512643  0.507630  0.508970  0.509804  0.510782  0.511774  0.495740
643  0.513927  0.508911  0.510206  0.511011  0.511967  0.512948  0.496902

     lmk090_x  lmk091_x  lmk092_x  lmk093_x  lmk094_x  lmk095_x  lmk096_x  \
0    0.502165  0.500286  0.498424  0.490238  0.423330  0.529469  0.498901
1    0.501410  0.499494  0.497679  0.489374  0.424264  0.528702  0.498052
2    0.502767  0.500830  0.499009  0.490419  0.423738  0.530129  0.499369
3    0.503016  0.501057  0.499251  0.490822  0.425330  0.530224  0.499723
4    0.503582  0.501657  0.499844  0.491318  0.425790  0.530825  0.500238
..        ...       ...       ...       ...       ...       ...       ...
639  0.497808  0.495644  0.493650  0.486581  0.427008  0.526844  0.494810
640  0.497349  0.495287  0.493334  0.485999  0.426264  0.526254  0.494246
641  0.495951  0.493892  0.491932  0.484493  0.423926  0.524753  0.492845
642  0.494378  0.492326  0.490381  0.483189  0.422966  0.524149  0.491142
643  0.495530  0.493440  0.491469  0.484218  0.422634  0.525455  0.492287

     lmk097_x  lmk098_x  lmk099_x  lmk100_x  lmk101_x  lmk102_x  lmk103_x  \
0    0.497249  0.517398  0.502543  0.515867  0.490893  0.476265  0.497454
1    0.496364  0.516402  0.501238  0.514845  0.490474  0.476150  0.495952
2    0.497718  0.517779  0.502435  0.516217  0.491081  0.476631  0.497098
3    0.498058  0.517997  0.502840  0.516464  0.491762  0.477392  0.497550
4    0.498591  0.518549  0.503346  0.516993  0.492156  0.477775  0.498026
..        ...       ...       ...       ...       ...       ...       ...
639  0.492994  0.514549  0.499795  0.513090  0.491636  0.476490  0.495216
640  0.492499  0.513954  0.499161  0.512486  0.490978  0.475878  0.494589
641  0.491101  0.512501  0.497653  0.511004  0.489236  0.474081  0.493042
642  0.489382  0.511698  0.496725  0.510241  0.488550  0.473330  0.492248
643  0.490500  0.512736  0.497583  0.511248  0.489291  0.474021  0.493063

     lmk104_x  lmk105_x  lmk106_x  lmk107_x  lmk108_x  lmk109_x  lmk110_x  \
0    0.452071  0.457345  0.463364  0.493381  0.504572  0.502273  0.499329
1    0.452445  0.458285  0.464587  0.493212  0.505101  0.502236  0.498801
2    0.452223  0.458236  0.464843  0.494331  0.505782  0.502983  0.499514
3    0.453378  0.459253  0.465819  0.494645  0.506471  0.503767  0.500430
4    0.453550  0.459354  0.465876  0.495205  0.506709  0.504023  0.500668
..        ...       ...       ...       ...       ...       ...       ...
639  0.459176  0.463572  0.468733  0.488885  0.510150  0.509031  0.507316
640  0.458581  0.462969  0.468114  0.488483  0.509505  0.508366  0.506593
641  0.456547  0.461059  0.466267  0.486948  0.507745  0.506559  0.504727
642  0.456386  0.460841  0.466020  0.485493  0.507358  0.506242  0.504493
643  0.456033  0.460898  0.466372  0.486610  0.508024  0.506599  0.504555

     lmk111_x  lmk112_x  lmk113_x  lmk114_x  lmk115_x  lmk116_x  lmk117_x  \
0    0.462697  0.441879  0.500621  0.450921  0.506953  0.505997  0.432244
1    0.463363  0.442358  0.500880  0.451823  0.506652  0.504516  0.432658
2    0.463938  0.442565  0.501505  0.452301  0.507494  0.505905  0.432735
3    0.465192  0.443765  0.502429  0.453653  0.508132  0.506235  0.433986
4    0.465314  0.444087  0.502679  0.453774  0.508507  0.506697  0.434328
..        ...       ...       ...       ...       ...       ...       ...
639  0.466248  0.444307  0.504658  0.455524  0.508846  0.503337  0.434365
640  0.465566  0.443780  0.503846  0.454894  0.508176  0.502777  0.433847
641  0.463545  0.441708  0.501931  0.452813  0.506399  0.501213  0.431730
642  0.463105  0.441202  0.501529  0.452524  0.505880  0.500623  0.431137
643  0.463424  0.441276  0.502215  0.452559  0.506688  0.501578  0.431084

     lmk118_x  lmk119_x  lmk120_x  lmk121_x  lmk122_x  lmk123_x  lmk124_x  \
0    0.448366  0.460197  0.477390  0.490074  0.499750  0.519498  0.433941
1    0.448670  0.460368  0.477427  0.489963  0.499609  0.519183  0.434090
2    0.448967  0.460720  0.477887  0.490515  0.500277  0.520239  0.434130
3    0.450070  0.461685  0.478741  0.491304  0.501025  0.520778  0.435307
4    0.450388  0.462006  0.479074  0.491642  0.501365  0.521213  0.435690
..        ...       ...       ...       ...       ...       ...       ...
639  0.449958  0.461273  0.478827  0.491930  0.502013  0.522348  0.434413
640  0.449423  0.460710  0.478187  0.491246  0.501313  0.521685  0.433818
641  0.447421  0.458797  0.476355  0.489446  0.499509  0.519899  0.431769
642  0.446863  0.458198  0.475723  0.488838  0.498964  0.519470  0.430880
643  0.447083  0.458635  0.476334  0.489502  0.499667  0.520360  0.431069

     lmk125_x  lmk126_x  lmk127_x  lmk128_x  lmk129_x  lmk130_x  lmk131_x  \
0    0.443262  0.525202  0.501637  0.421623  0.506957  0.496440  0.455766
1    0.444016  0.524289  0.500767  0.422688  0.506846  0.495077  0.456707
2    0.444333  0.525818  0.501608  0.421710  0.507583  0.496070  0.457217
3    0.445673  0.525932  0.502168  0.423286  0.508301  0.496565  0.458614
4    0.445850  0.526491  0.502594  0.423667  0.508649  0.497031  0.458670
..        ...       ...       ...       ...       ...       ...       ...
639  0.447758  0.522317  0.501640  0.426991  0.509679  0.494377  0.460106
640  0.447178  0.521761  0.500994  0.426400  0.508964  0.493716  0.459435
641  0.445071  0.520226  0.499317  0.424064  0.507143  0.492159  0.457334
642  0.444796  0.519671  0.498648  0.423504  0.506657  0.491310  0.457007
643  0.444731  0.520923  0.499471  0.422974  0.507423  0.492133  0.457151

     lmk132_x  lmk133_x  lmk134_x  lmk135_x  lmk136_x  lmk137_x  lmk138_x  \
0    0.505337  0.425904  0.500499  0.513135  0.452356  0.452249  0.424500
1    0.503884  0.426933  0.500850  0.512092  0.453109  0.453526  0.424956
2    0.505152  0.426634  0.501499  0.513446  0.453616  0.453869  0.424761
3    0.505527  0.428153  0.502463  0.513747  0.454548  0.454912  0.426102
4    0.505974  0.428652  0.502694  0.514208  0.454991  0.455361  0.426543
..        ...       ...       ...       ...       ...       ...       ...
639  0.503340  0.428575  0.504975  0.511691  0.450382  0.451084  0.426277
640  0.502761  0.427789  0.504152  0.511146  0.449634  0.450291  0.425663
641  0.501185  0.425512  0.502182  0.509531  0.447661  0.448196  0.423473
642  0.500589  0.424274  0.501840  0.509061  0.446055  0.446585  0.422521
643  0.501509  0.424079  0.502509  0.510101  0.446695  0.447064  0.422424

     lmk139_x  lmk140_x  lmk141_x  lmk142_x  lmk143_x  lmk144_x  lmk145_x  \
0    0.441490  0.429642  0.489908  0.525843  0.493344  0.433359  0.470546
1    0.442011  0.430411  0.490923  0.525030  0.492605  0.433939  0.471162
2    0.442126  0.429882  0.491962  0.526499  0.493355  0.433965  0.471874
3    0.443171  0.431257  0.492376  0.526635  0.493942  0.435278  0.473104
4    0.443668  0.431532  0.492880  0.527212  0.494372  0.435600  0.473191
..        ...       ...       ...       ...       ...       ...       ...
639  0.440167  0.434470  0.485472  0.523171  0.492862  0.437011  0.474366
640  0.439371  0.433945  0.484896  0.522583  0.492214  0.436522  0.473641
641  0.437302  0.431765  0.483095  0.521073  0.490546  0.434369  0.471680
642  0.435674  0.431426  0.481833  0.520468  0.489777  0.433926  0.471208
643  0.436129  0.431076  0.482924  0.521694  0.490568  0.433749  0.471603

     lmk146_x  lmk147_x  lmk148_x  lmk149_x  lmk150_x  lmk151_x  lmk152_x  \
0    0.478445  0.492969  0.435684  0.506672  0.478018  0.465901  0.527740
1    0.478919  0.491991  0.435746  0.507910  0.479454  0.467242  0.527288
2    0.479626  0.493288  0.435698  0.508750  0.480336  0.467970  0.528403
3    0.480766  0.493632  0.436830  0.508953  0.481042  0.468842  0.529083
4    0.480909  0.494184  0.437266  0.509524  0.481467  0.469262  0.529449
..        ...       ...       ...       ...       ...       ...       ...
639  0.482251  0.488342  0.435194  0.501679  0.475094  0.463887  0.535528
640  0.481500  0.487931  0.434496  0.501072  0.474416  0.463169  0.534733
641  0.479573  0.486549  0.432477  0.499332  0.472518  0.461179  0.532961
642  0.479075  0.484806  0.431222  0.497996  0.471116  0.459667  0.532549
643  0.479531  0.485863  0.431555  0.499236  0.471932  0.460298  0.533081

     lmk153_x  lmk154_x  lmk155_x  lmk156_x  lmk157_x  lmk158_x  lmk159_x  \
0    0.526591  0.486206  0.493414  0.498112  0.436734  0.492523  0.484655
1    0.527571  0.486631  0.493834  0.498473  0.437462  0.493001  0.485122
2    0.528166  0.487279  0.494456  0.499078  0.437515  0.493776  0.485955
3    0.528095  0.488338  0.495458  0.500042  0.438860  0.494823  0.487064

In [16]:
framewise_disp_no

,frame,time,lmk001,lmk002,lmk003,lmk004,lmk005,lmk006,lmk007,lmk008,lmk009,lmk010,lmk011,lmk012,lmk013,lmk014,lmk015,lmk016,lmk017,lmk018,lmk019,lmk020,lmk021,lmk022,lmk023,lmk024,lmk025,lmk026,lmk027,lmk028,lmk029,lmk030,lmk031,lmk032,lmk033,lmk034,lmk035,lmk036,lmk037,lmk038,lmk039,lmk040,lmk041,lmk042,lmk043,lmk044,lmk045,lmk046,lmk047,lmk048,lmk049,lmk050,lmk051,lmk052,lmk053,lmk054,lmk055,lmk056,lmk057,lmk058,lmk059,lmk060,lmk061,lmk062,lmk063,lmk064,lmk065,lmk066,lmk067,lmk068,lmk069,lmk070,lmk071,lmk072,lmk073,lmk074,lmk075,lmk076,lmk077,lmk078,lmk079,lmk080,lmk081,lmk082,lmk083,lmk084,lmk085,lmk086,lmk087,lmk088,lmk089,lmk090,lmk091,lmk092,lmk093,lmk094,lmk095,lmk096,lmk097,lmk098,lmk099,lmk100,lmk101,lmk102,lmk103,lmk104,lmk105,lmk106,lmk107,lmk108,lmk109,lmk110,lmk111,lmk112,lmk113,lmk114,lmk115,lmk116,lmk117,lmk118,lmk119,lmk120,lmk121,lmk122,lmk123,lmk124,lmk125,lmk126,lmk127,lmk128,lmk129,lmk130,lmk131,lmk132,lmk133,lmk134,lmk135,lmk136,lmk137,lmk138,lmk139,lmk140,lmk141,lmk142,lmk143,lmk144,lmk145,lmk146,lmk147,lmk148,lmk149,lmk150,lmk151,lmk152,lmk153,lmk154,lmk155,lmk156,lmk157,lmk158,lmk159,lmk160,lmk161,lmk162,lmk163,lmk164,lmk165,lmk166,lmk167,lmk168,lmk169,lmk170,lmk171,lmk172,lmk173,lmk174,lmk175,lmk176,lmk177,lmk178,lmk179,lmk180,lmk181,lmk182,lmk183,lmk184,lmk185,lmk186,lmk187,lmk188,lmk189,lmk190,lmk191,lmk192,lmk193,lmk194,lmk195,lmk196,lmk197,lmk198,lmk199,lmk200,lmk201,lmk202,lmk203,lmk204,lmk205,lmk206,lmk207,lmk208,lmk209,lmk210,lmk211,lmk212,lmk213,lmk214,lmk215,lmk216,lmk217,lmk218,lmk219,lmk220,lmk221,lmk222,lmk223,lmk224,lmk225,lmk226,lmk227,lmk228,lmk229,lmk230,lmk231,lmk232,lmk233,lmk234,lmk235,lmk236,lmk237,lmk238,lmk239,lmk240,lmk241,lmk242,lmk243,lmk244,lmk245,lmk246,lmk247,lmk248,lmk249,lmk250,lmk251,lmk252,lmk253,lmk254,lmk255,lmk256,lmk257,lmk258,lmk259,lmk260,lmk261,lmk262,lmk263,lmk264,lmk265,lmk266,lmk267,lmk268,lmk269,lmk270,lmk271,lmk272,lmk273,lmk274,lmk275,lmk276,lmk277,lmk278,lmk279,lmk280,lmk281,lmk282,lmk283,lmk284,lmk285,lmk286,lmk287,lmk288,lmk289,lmk290,lmk291,lmk292,lmk293,lmk294,lmk295,lmk296,lmk297,lmk298,lmk299,lmk300,lmk301,lmk302,lmk303,lmk304,lmk305,lmk306,lmk307,lmk308,lmk309,lmk310,lmk311,lmk312,lmk313,lmk314,lmk315,lmk316,lmk317,lmk318,lmk319,lmk320,lmk321,lmk322,lmk323,lmk324,lmk325,lmk326,lmk327,lmk328,lmk329,lmk330,lmk331,lmk332,lmk333,lmk334,lmk335,lmk336,lmk337,lmk338,lmk339,lmk340,lmk341,lmk342,lmk343,lmk344,lmk345,lmk346,lmk347,lmk348,lmk349,lmk350,lmk351,lmk352,lmk353,lmk354,lmk355,lmk356,lmk357,lmk358,lmk359,lmk360,lmk361,lmk362,lmk363,lmk364,lmk365,lmk366,lmk367,lmk368,lmk369,lmk370,lmk371,lmk372,lmk373,lmk374,lmk375,lmk376,lmk377,lmk378,lmk379,lmk380,lmk381,lmk382,lmk383,lmk384,lmk385,lmk386,lmk387,lmk388,lmk389,lmk390,lmk391,lmk392,lmk393,lmk394,lmk395,lmk396,lmk397,lmk398,lmk399,lmk400,lmk401,lmk402,lmk403,lmk404,lmk405,lmk406,lmk407,lmk408,lmk409,lmk410,lmk411,lmk412,lmk413,lmk414,lmk415,lmk416,lmk417,lmk418,lmk419,lmk420,lmk421,lmk422,lmk423,lmk424,lmk425,lmk426,lmk427,lmk428,lmk429,lmk430,lmk431,lmk432,lmk433,lmk434,lmk435,lmk436,lmk437,lmk438,lmk439,lmk440,lmk441,lmk442,lmk443,lmk444,lmk445,lmk446,lmk447,lmk448,lmk449,lmk450,lmk451,lmk452,lmk453,lmk454,lmk455,lmk456,lmk457,lmk458,lmk459,lmk460,lmk461,lmk462,lmk463,lmk464,lmk465,lmk466,lmk467,lmk468,overall,lower_face,upper_face,lips,eyebrows,mouth_openness
0,0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.137022
1,1,0.033333,0.001435,0.002616,0.001168,0.002408,0.002865,0.002727,0.002213,0.001655,0.001335,0.001686,0.009454,0.001754,0.002072,0.002091,0.003390,0.003809,0.004288,0.004836,0.005149,0.002468,0.002193,0.003972,0.000862,0.000961,0.001192,0.001444,0.000945,0.000134,0.000141,0.000377,0.000856,0.001227,0.005164,0.001540,0.001457,0.001135,0.000721,0.001132,0.001922,0.001199,0.001651,0.001927,0.001924,0.003111,0.002736,0.002831,0.000783,0.001499,0.002670,0.002508,0.000065,0.002726,0.001389,0.001076,0.005317,0.001546,0.000329,0.002274,0.003549,0.002496,0.001841,0.002510,0.002548,0.001160,0.002320,0.001790,0.001457,0.007946,0.003501,0.004559,0.000925,0.002699,0.001550,0.001581,0.001734,0.002197,0.002501,0.002806,0.002552,0.002851,0.001865,0.001884,0.001927,0.005056,0.004778,0.004194,0.003568,0.003276,0.002742,0.002844,0.003255,0.003503,0.000675,0.001508,0.002100,0.002640,0.002681,0.001369,0.001764,0.001593,0.001278,0.000768,0.002253,0.006525,0.004013,0.001284,0.003597,0.001453,0.005603,0.009019,0.001334,0.001068,0.000979,0.001192,0.001626,0.002888,0.000825,0.000950,0.000829,0.000902,0.001073,0.001302,0.001919,0.000342,0.000949,0.002379,0.001791,0.001509,0.001393,0.001934,0.001350,0.002743,0.002361,0.000956,0.002603,0.004180,0.005024,0.000787,0.003633,0.002212,0.005570,0.002079,0.001342,0.001084,0.001440,0.001186,0.002941,0.001159,0.006164,0.005768,0.005454,0.006157,0.006202,0.001161,0.001114,0.001052,0.001064,0.001183,0.001056,0.001119,0.001231,0.001367,0.002885,0.001619,0.000298,0.000620,0.002662,0.000525,0.001547,0.004727,0.005119,0.005902,0.004494,0.001089,0.002005,0.006076,0.005964,0.001832,0.003003,0.003310,0.003807,0.004321,0.004317,0.002123,0.002080,0.001947,0.001361,0.000849,0.001797,0.000658,0.000818,0.002148,0.002473,0.001003,0.004740,0.002508,0.002181,0.002366,0.002157,0.005775,0.005474,0.005334,0.003355,0.001043,0.004089,0.000094,0.000448,0.001073,0.005726,0.002108,0.003975,0.004606,0.002479,0.002035,0.002893,0.002829,0.001066,0.001918,0.002965,0.002749,0.002882,0.000303,0.000766,0.000659,6.303718e-04,0.000920,0.001358,0.000788,0.001140,0.001025,0.000851,0.000940,0.000995,0.001087,0.000960,0.002434,0.002265,0.002789,0.002431,0.002754,0.001967,0.002373,0.002114,0.000916,0.001101,0.001391,0.001566,0.001166,0.002376,0.001974,0.002134,0.004378,0.001340,0.001346,0.001449,0.001788,0.001432,0.001050,0.000973,0.001352,0.001559,0.001674,0.005640,0.002016,0.001744,0.001779,0.000518,0.001057,0.001831,0.001276,0.001866,0.001968,0.002212,0.003608,0.002650,0.002719,0.002189,0.001476,0.001865,0.001768,0.000905,0.002676,0.001652,0.002134,0.005771,0.001456,0.001095,0.002847,0.004015,0.001662,0.001211,0.002979,0.003140,0.002524,0.001520,0.001573,0.001729,0.008362,0.004204,0.005228,0.002486,0.003495,0.001537,0.001694,0.002072,0.001339,0.003032,0.003227,0.003164,0.002439,0.002078,0.002012,0.001955,0.005222,0.004779,0.004278,0.003654,0.003309,0.003218,0.003151,0.003473,0.003746,0.000936,0.001907,0.003137,0.003232,0.000852,0.000863,0.001099,0.001212,0.000772,0.001447,0.007067,0.004808,0.002063,0.004051,0.001656,0.005933,0.009231,0.001627,0.001566,0.001428,0.002107,0.001637,0.002278,0.001423,0.001181,0.000999,0.000932,0.001208,0.001418,0.002062,0.001374,0.001922,0.002433,0.001480,0.001422,0.001607,0.001188,0.002009,0.002161,0.002694,0.001443,0.002387,0.004618,0.005320,0.001691,0.004123,0.002662,0.005985,0.002074,0.001083,0.001792,0.001731,0.001571,0.003357,0.001969,0.006290,0.006109,0.005790,0.001612,0.001616,0.001526,0.002142,0.001670,0.001757,0.001771,0.001755,0.001831,0.002903,0.001876,0.000070,0.001934,-0.000099,0.005192,0.005544,0.006130,0.004931,0.001595,0.001884,0.006238,0.002425,0.003171,0.003454,0.003951,0.004388,0.004588,0.002608,0.002463,0.002420,0.001915,0.001907,0.001848,0.001175,0.001341,0.002548,0.003129,0.001230,0.005026,0.002194,0.001833,0.005540,0.004010,0.000486,0.004578,0.000721,0.000644,0.001741,0.005930,0.001625,0.004373,0.005091,0.003174,0.002740,0.003394,0.003358,0.001674,0.001731,0.002476,0.001825,0.002609,0.000685,0.000975,0.001209,0.001641,0.002047,0.001860,0.001401,0.001405,0.001131,0.001061,0.001155,0.001349,0.001452,0.001295,0.001548,0.002093,0.002629,0.002475,0.002606,0.001133,0.002445,0.002192,0.001411,0.001455,0.001674,0.001920,0.001909,0.002400,0.003261,0.001921,0.002719,0.001555,0.185313
2,2,0.066667,0.001487,0.001232,0.001313,0.001321,0.001246,0.001320,0.001437,0.002206,0.001523,0.002382,0.001369,0.001458,0.001453,0.001436,0.001393,0.001371,0.001295,0.001244,0.001422,0.001250,0.001335,0.001225,0.002128,0.002099,0.001948,0.001924,0.002033,0.000692,0.000676,0.000663,0.000848,0.001720,0.001926,0.002255,0.002067,0.001204,0.001588,0.001477,0.001411,0.001484,0.001488,0.001437,0.001500,0.001804,0.001253,0.001268,0.000609,0.001681,0.001393,0.001439,0.001568,0.001262,0.002181,0.001443,0.000411,0.001798,0.000984,0.001884,0.003932,0.001420,0.001471,0.001685,0.001707,0.001742,0.001480,0.002460,0.002811,0.000792,0.000499,0.001532,0.000750,0.000508,0.001434,0.001451,0.001465,0.001482,0.001687,0.001636,0.001697,0.001289,0.001491,0.001363,0.001383,0.001444,0.001249,0.001302,0.001337,0.001409,0.001531,0.001519,0.001503,0.001539,0.001560,0.003583,0.001241,0.001660,0.001618,0.001417,0.001550,0.001464,0.001643,0.001462,0.001540,0.000313,0.001132,0.002402,0.001646,0.002610,0.001307,0.001118,0.001923,0.001721,0.001907,0.000677,0.001610,0.001234,0.001965,0.001671,0.001588,0.001646,0.001841,0.001775,0.001390,0.002181,0.000360,0.001287,0.001562,0.002629,0.001660,0.001629,0.001660,0.001246,0.003878,0.002013,0.001233,0.002866,0.003229,0.002966,0.003233,0.001235,0.001996,0.001279,0.001625,0.001399,0.002136,0.002158,0.001661,0.002537,0.001833,0.002406,0.002734,0.001438,0.001646,0.002170,0.002145,0.002014,0.000525,0.003057,0.003567,0.003685,0.003419,0.003002,0.001995,0.002191,0.001472,0.001560,0.001397,0.001537,0.000857,0.002541,0.002264,0.001734,0.003658,0.002421,0.001434,0.001584,0.002088,0.003331,0.001403,0.001357,0.001376,0.001401,0.001505,0.001590,0.001551,0.001556,0.001597,0.002050,0.001463,0.000723,0.001403,0.001546,0.002636,0.000501,0.001804,0.001392,0.001442,0.001511,0.001357,0.001618,0.001593,0.001643,0.002052,0.001673,0.001938,0.001585,0.001621,0.001880,0.001725,0.001487,0.002294,0.002115,0.002046,0.002813,0.002303,0.003480,0.001675,0.001497,0.001276,0.001383,0.001278,0.000153,0.000716,0.000783,4.141544e-04,0.000107,0.001368,0.002586,0.001825,0.001730,0.001893,0.002002,0.001915,0.001793,0.003180,0.001452,0.001308,0.001289,0.001340,0.001307,0.001503,0.001316,0.001323,0.001704,0.001472,0.001360,0.002612,0.001148,0.001425,0.003532,0.001244,0.001608,0.002908,0.002979,0.002868,0.003237,0.002735,0.001443,0.001471,0.001682,0.002133,0.002526,0.001407,0.003763,0.002215,0.001991,0.001680,0.001524,0.001514,0.001523,0.001434,0.001521,0.001472,0.001158,0.001221,0.001259,0.001026,0.001991,0.001253,0.001367,0.001876,0.001323,0.001864,0.001421,0.001246,0.001924,0.001645,0.001235,0.003341,0.001215,0.001319,0.001213,0.001219,0.001608,0.001220,0.002291,0.002614,0.001335,0.001344,0.001861,0.000985,0.001271,0.001504,0.001525,0.001452,0.001307,0.001221,0.001338,0.001277,0.001241,0.001434,0.001474,0.001523,0.001304,0.001217,0.001296,0.001378,0.001450,0.001377,0.001366,0.001337,0.001324,0.001500,0.003134,0.001351,0.001304,0.001358,0.001288,0.001328,0.001978,0.001920,0.001340,0.001194,0.001612,0.002119,0.001212,0.002548,0.001626,0.001385,0.002996,0.002154,0.002567,0.002008,0.001910,0.001243,0.002257,0.002058,0.001930,0.002126,0.002226,0.002199,0.001559,0.002242,0.001374,0.001237,0.001729,0.002288,0.002031,0.001380,0.003117,0.001304,0.003333,0.002718,0.001320,0.002229,0.002635,0.002785,0.002790,0.001725,0.001429,0.001239,0.001687,0.001973,0.003203,0.003163,0.001278,0.002414,0.001408,0.001689,0.002062,0.003097,0.002923,0.002777,0.001226,0.003894,0.004645,0.004905,0.004800,0.004408,0.001934,0.003316,0.001426,0.001237,0.001455,0.001816,0.001539,0.001378,0.003166,0.003155,0.001631,0.001437,0.002984,0.001413,0.001376,0.001323,0.001259,0.001269,0.001394,0.001372,0.001338,0.001364,0.002111,0.001719,0.001328,0.002007,0.001337,0.002329,0.000931,0.001357,0.001548,0.001516,0.001431,0.001277,0.001470,0.001237,0.001795,0.001595,0.001807,0.001441,0.001525,0.001562,0.001421,0.001393,0.002525,0.001843,0.003093,0.001502,0.001705,0.001246,0.001237,0.001258,0.000795,0.000881,0.000867,0.001049,0.001526,0.002460,0.002557,0.002532,0.002388,0.002534,0.002551,0.002466,0.002262,0.002718,0.001230,0.001458,0.001243,0.001267,0.001252,0.001276,0.001272,0.001242,0.002283,0.001937,0.001735,0.004079,0.002549,0.001756,0.001737,0.001768,0.001434,0.001619,0.185008
3,3,0.100000,0.000984,0.001076,0.001091,0.001109,0.001103,0.001108,0.001062,0.001333,0.000247,0.000120,0.000259,0.000966,0.000939,0.000922,0.001168,0.001177,0.001169,0.001075,0.000703,0.001071,0.001036,0.000811,0.001221,0.001232,0.001216,0.001278,0.001204,0.001045,0.000979,0.001153,0.001250,0.001126,0.000216,0.001404,0.000895,0.000995,0.000970,0.000987,0.000889,0.000958,0.000948,0.000907,0.000881,0.000786,0.001062,0.001079,0.000858,0.001094,0.000996,0.001000,0.000990,0.001096,0.000505,0.000725,0.000660,0.000195,0.000986,0.000885,0.000814,0.000989,0.001025,0.000900,0.000904,0.000646,0.000970,0.000318,0.000315,0.000393,0.000628,0.000325,0.000789,0.000765,0.000928,0.000933,0.000900,0.000985,0.000930,0.000945,0.000928,0.001050,0.000880,0.000883,0.000910,0.000681,0.001026,0.001110,0.001137,0.001129,0.001003,0.000978,0.000947,0.000907,0.000925,0.000975,0.001053,0.000950,0.000945,0.001023,0.000928,0.001006,0.001051,0.001016,0.000973,0.000529,0.000467,0.000456,0.000703,0.000202,0.000290,0.000306,0.001226,0.001024,0.001182,0.001108,0.001113,0.001014,0.001001,0.001039,0.001007,0.001056,0.001086,0.001118,0.001063,0.001009,0.000953,0.001084,0.001065,0.000919,0.001115,0.000957,0.001300,0.001023,0.000925,0.001229,0.001065,0.000604,0.000522,0.000960,0.000744,0.000856,0.000108,0.001045,0.001005,0.000937,0.001272,0.001279,0.000927,0.000984,-0.000163,0.000187,0.000337,0.000271,-0.000295,0.001280,0.001237,0.001205,0.000882,0.001437,0.001540,0.001615,0.001638,0.001566,0.000875,0.001306,0.001078,0.000937,0.001010,0.001025,0.000687,0.000418,0.000256,-0.000030,0.000687,0.001311,0.001113,-0.000096,0.000034,0.000934,0.001076,0.001035,0.001017,0.000942,0.000669,0.000903,0.000910,0.000903,0.000906,0.000956,0.001092,0.000866,0.001076,0.000887,0.000863,0.000713,0.000431,0.001119,0.001103,0.001130,0.001057,0.000174,0.000452,0.000440,0.000697,0.000949,0.000527,0.000950,0.000910,0.000902,0.000197,0.001036,0.000559,0.000344,0.000841,0.000929,0.000788,0.000844,0.000895,0.001089,0.001043,0.000992,0.001062,0.000581,0.000610,0.000761,9.290044e-04,0.001053,0.001129,0.000956,0.001142,0.001094,0.001150,0.001156,0.001152,0.001123,0.000964,0.000970,0.001082,0.001075,0.001043,0.001060,0.000962,0.001052,0.001056,0.001141,0.001070,0.001037,0.001493,0.001248,0.001165,0.001419,0.001073,0.001621,0.001315,0.001341,0.001333,0.001410,0.001242,0.001033,0.000988,0.001076,0.001174,0.001449,0.000461,0.001452,0.001803,0.001425,0.001301,0.001054,0.000969,0.001156,0.001221,0.001068,0.001154,0.001215,0.001119,0.001139,0.000848,0.001229,0.001193,0.001242,0.001452,0.001137,0.000314,0.000509,0.001316,0.000217,0.001025,0.001372,0.001647,0.001177,0.001151,0.001357,0.001322,0.000562,0.001215,0.000244,0.000220,0.000645,0.000990,0.000455,0.000949,0.001318,0.001001,0.001099,0.001174,0.001153,0.001340,0.001297,0.001321,0.001116,0.001137,0.001060,0.000975,0.000804,0.001140,0.001200,0.001216,0.001201,0.001274,0.001280,0.001254,0.001214,0.001242,0.001952,0.001303,0.001314,0.001141,0.001197,0.001137,0.001281,0.001320,0.001261,0.000990,0.000708,0.000377,0.001036,0.000147,0.000342,0.000398,0.001375,0.001560,0.001212,0.001199,0.001207,0.001144,0.001671,0.001528,0.001446,0.001349,0.001282,0.001219,0.001055,0.001662,0.001159,0.001093,0.001246,0.001977,0.001167,0.001256,0.001380,0.001195,0.001817,0.001258,0.001155,0.001145,0.000994,0.001861,0.001447,0.001603,0.000176,0.001058,0.001280,0.001552,0.001369,0.001362,0.001295,0.001650,-0.000253,0.000196,0.000548,0.001329,0.001304,0.001258,0.001274,0.001477,0.001593,0.001677,0.001684,0.001617,0.001852,0.001386,0.001194,0.001160,0.001118,0.000771,0.000444,0.000030,0.001408,0.001343,0.001161,-0.000070,0.001819,0.001246,0.001235,0.001250,0.001175,0.000919,0.001243,0.001272,0.001298,0.001328,0.001487,0.001128,0.000891,0.001075,0.001222,0.001473,0.000717,0.000702,0.001128,0.001206,0.000568,0.001127,0.001285,0.000874,0.001359,0.001309,0.001387,0.000322,0.001241,0.000960,0.000664,0.001319,0.001605,0.001278,0.001704,0.001362,0.001211,0.001131,0.001173,0.001158,0.000641,0.000596,0.000668,0.000801,0.000981,0.001380,0.001855,0.001444,0.001384,0.001326,0.001298,0.001202,0.001165,0.001990,0.001195,0.001178,0.001113,0.001101,0.001101,0.001182,0.001086,0.001079,0.001141,0.001073,0.001043,0.001521,0.001260,0.001023,0.000923,0.001077,0.001076,0.000626,0.195894

In [17]:
summary_no

,overall_mean,lower_face_mean,upper_face_mean,lips_mean,eyebrows_mean,mouth_openness_mean,overall_std,lower_face_std,upper_face_std,lips_std,eyebrows_std,mouth_openness_std
0,0.003464,0.003899,0.003218,0.004297,0.003928,0.878355,0.002627,0.00286,0.002709,0.003284,0.003474,0.662627

# eye blink

In [3]:
import openwillis.face as owf

ear, blinks, summary = owf.eye_blink_rate(video = 'video.mov')

ModuleNotFoundError: No module named 'openwillis'

In [4]:
ear

     frame       ear
0        1  0.770658
1        2  0.326757
2        3  0.155663
3        4 -0.100537
4        5 -0.047135
..     ...       ...
639    640  0.707688
640    641  0.681688
641    642  0.505838
642    643  0.699741
643    644  0.841387

[644 rows x 2 columns]

In [5]:
blinks

,blink_peak_frame,blink_starting_frame,blink_ending_frame,blink_peak_time,blink_starting_time,blink_ending_time
0,29,28,33,0.966667,0.933333,1.100000
1,54,51,56,1.800000,1.700000,1.866667
2,84,80,85,2.800000,2.666667,2.833333
3,107,105,110,3.566667,3.500000,3.666667
4,151,149,153,5.033333,4.966667,5.100000
5,186,183,188,6.200000,6.100000,6.266667
6,205,202,206,6.833333,6.733333,6.866667
7,263,262,265,8.766667,8.733333,8.833333
8,302,301,305,10.066667,10.033333,10.166667
9,321,308,323,10.700000,10.266667,10.766667
10,330,328,332,11.000000,10.933333,11.066667
11,346,344,351,11.533333,11.466667,11.700000
12,359,357,361,11.966667,11.900000,12.033333
13,384,382,386,12.800000,12.733333,12.866667
14,490,475,491,16.333333,15.833333,16.366667
15,509,507,513,16.966667,16.900000,17.100000
16,536,535,538,17.866667,17.833333,17.933333
17,609,607,612,20.300000,20.233333,20.400000

In [6]:
summary

   blinks  blink_rate
0    18.0   50.310559

# head_movement

In [1]:
import openwillis.face as owf

print("has head_movement:", hasattr(owf, "head_movement"))
owf.head_movement

has head_movement: True

In [ ]:
import openwillis.face as owf
# 11.7mb video 1080p MPEG-4 AAC, H.264, stereo, duration 21s
# frames_per_second=1 - 14.4s
# frames_per_second=3 - 1m4s - for 30fps video result will appears only 3 times - every 10 frames
# frames_per_second=10 - 1m43s
# frames_per_second=15 - 2m34s
# frames_per_second=25 - 5m17s
# frames_per_second=30 - 5m7s (3m33s with bounding boxes + 1m13s for bbox)

head_movement_df, summary_df = owf.head_movement(
	video_path='video.mov',
	frames_per_second=30, # for 30fps video result will appears only 3 times - every 10 frames
	normalize_by_bb_size=False,
	bbox_list=[],
	padding_percent=0.1,
)

print("head_movement_df shape:", head_movement_df.shape)
print("summary_df shape:", summary_df.shape)
# display(head_movement_df.head())
# display(summary_df)

INFO:root:Loading Face model: retinaface

INFO:root:Loading Facial Landmark model: mobilefacenet
INFO:root:Loading facepose model: img2pose
INFO:root:Loading AU model: xgb
INFO:root:Loading emotion model: resmasknet
INFO:root:Loading Identity model: facenet
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...
INFO:root:img2pose: RESCALING WARNING: img2pose has a min img size of 400 and a max img size of 1400 but checked value is torch.Size([1080, 1920]).
INFO:root:detecting poses...

head_movement_df shape: (644, 15)
summary_df shape: (1, 10)

In [16]:
head_movement_df.head(10)

,frame,bb_x1,bb_y1,bb_x2,bb_y2,face_confidence,pitch,roll,yaw,time,bb_center_x,bb_center_y,euclidean_angle,euclidean_angle_disp,xy_disp
0,0.0,783.0,172.0,1215.0,712.0,0.974904,3.937711,-0.415654,-2.253198,0.000000,999.0,442.0,4.562622,NaN,0.000000
1,1.0,783.0,172.0,1215.0,712.0,0.975215,4.039510,-0.379902,-2.209774,0.033333,999.0,442.0,4.626246,0.063624,0.000000
2,2.0,783.0,175.0,1215.0,712.0,0.976003,3.743224,-0.220821,-2.643445,0.066667,999.0,443.5,4.591722,0.034524,1.500000
3,3.0,785.0,180.0,1215.0,715.0,0.977276,3.255390,-0.480572,-2.542509,0.100000,1000.0,447.5,4.166587,0.425135,4.123106
4,4.0,788.0,178.0,1217.0,715.0,0.977967,2.753902,-0.612429,-2.362055,0.133333,1002.5,446.5,3.688723,0.477864,2.692582
5,5.0,785.0,178.0,1217.0,717.0,0.977067,3.251359,-0.486615,-2.306702,0.166667,1001.0,447.5,4.023826,0.335103,1.802776
6,6.0,785.0,180.0,1217.0,717.0,0.977178,3.310911,-0.463555,-2.173434,0.200000,1001.0,448.5,3.994703,0.029123,1.000000
7,7.0,783.0,178.0,1215.0,715.0,0.978057,3.083471,-0.511859,-2.201727,0.233333,999.0,446.5,3.831028,0.163674,2.828427
8,8.0,783.0,175.0,1215.0,715.0,0.977693,3.236027,-0.469041,-2.224964,0.266667,999.0,445.0,3.962307,0.131279,1.500000
9,9.0,777.0,178.0,1212.0,717.0,0.976975,3.856051,-0.408458,-2.449379,0.300000,994.5,447.5,4.593518,0.631211,5.147815

In [15]:
summary_df

,xy_disp_mean,pitch_mean,yaw_mean,roll_mean,euclidean_angle_disp_mean,xy_disp_std,pitch_std,yaw_std,roll_std,euclidean_angle_disp_std
0,5.610718,-0.897279,-0.801461,3.813777,0.746908,4.907547,4.751389,4.336846,2.139319,0.875035

## head movement with bboxes

In [ ]:
import openwillis.face as owf

bb_dict, facedata_df = owf.preprocess_face_video("video.mov", n_people=1) # 1m13.4s

26-05-21 10:07:51 - facenet_weights.h5 will be downloaded...

Downloading...
From: https://github.com/serengil/deepface_models/releases/download/v1.0/facenet_weights.h5
To: /Users/pelmeshek1706/.deepface/weights/facenet_weights.h5
100%|██████████| 92.2M/92.2M [00:01<00:00, 54.5MB/s]

In [ ]:
bbox_list = bb_dict[0]
bbox_list

[{'bb_x': 797.0,
  'bb_y': 184.0,
  'bb_w': 404.0,
  'bb_h': 513.0,
  'right_eye_x': 916.0,
  'right_eye_y': 385.0,
  'left_eye_x': 1102.0,
  'left_eye_y': 389.0,
  'frame_idx': 0},
 {'bb_x': 797.0,
  'bb_y': 186.0,
  'bb_w': 402.0,
  'bb_h': 510.0,
  'right_eye_x': 916.0,
  'right_eye_y': 384.0,
  'left_eye_x': 1102.0,
  'left_eye_y': 388.0,
  'frame_idx': 1},
 {'bb_x': 797.0,
  'bb_y': 188.0,
  'bb_w': 401.0,
  'bb_h': 508.0,
  'right_eye_x': 916.0,
  'right_eye_y': 384.0,
  'left_eye_x': 1102.0,
  'left_eye_y': 388.0,
  'frame_idx': 2},
 {'bb_x': 797.0,
  'bb_y': 190.0,
  'bb_w': 400.0,
  'bb_h': 505.0,
  'right_eye_x': 916.0,
  'right_eye_y': 384.0,
  'left_eye_x': 1102.0,
  'left_eye_y': 388.0,
  'frame_idx': 3},
 {'bb_x': 798.0,
  'bb_y': 192.0,
  'bb_w': 399.0,
  'bb_h': 503.0,
  'right_eye_x': 916.0,
  'right_eye_y': 384.0,
  'left_eye_x': 1102.0,
  'left_eye_y': 388.0,
  'frame_idx': 4},
 {'bb_x': 798.0,
  'bb_y': 194.0,
  'bb_w': 398.0,
  'bb_h': 501.0,
  'right_eye_x': 917.0,
  'right_eye_y': 384.0,
  'left_eye_x': 1102.0,
  'left_eye_y': 388.0,
  'frame_idx': 5},
 {'bb_x': 798.0,
  'bb_y': 196.0,
  'bb_w': 396.0,
  'bb_h': 498.0,
  'right_eye_x': 917.0,
  'right_eye_y': 384.0,
  'left_eye_x': 1102.0,
  'left_eye_y': 387.0,
  'frame_idx': 6},
 {'bb_x': 799.0,
  'bb_y': 198.0,
  'bb_w': 395.0,
  'bb_h': 496.0,
  'right_eye_x': 917.0,
  'right_eye_y': 384.0,
  'left_eye_x': 1102.0,
  'left_eye_y': 387.0,
  'frame_idx': 7},
 {'bb_x': 799.0,
  'bb_y': 200.0,
  'bb_w': 394.0,
  'bb_h': 493.0,
  'right_eye_x': 917.0,
  'right_eye_y': 384.0,
  'left_eye_x': 1102.0,
  'left_eye_y': 387.0,
  'frame_idx': 8},
 {'bb_x': 799.0,
  'bb_y': 202.0,
  'bb_w': 393.0,
  'bb_h': 491.0,
  'right_eye_x': 917.0,
  'right_eye_y': 384.0,
  'left_eye_x': 1102.0,
  'left_eye_y': 387.0,
  'frame_idx': 9},
 {'bb_x': 800.0,
  'bb_y': 204.0,
  'bb_w': 392.0,
  'bb_h': 489.0,
  'right_eye_x': 918.0,
  'right_eye_y': 384.0,
  'left_eye_x': 1103.0,
  'left_eye_y': 387.0,
  'frame_idx': 10},
 {'bb_x': 798.0,
  'bb_y': 201.0,
  'bb_w': 394.0,
  'bb_h': 495.0,
  'right_eye_x': 917.0,
  'right_eye_y': 383.0,
  'left_eye_x': 1103.0,
  'left_eye_y': 386.0,
  'frame_idx': 11},
 {'bb_x': 797.0,
  'bb_y': 199.0,
  'bb_w': 396.0,
  'bb_h': 502.0,
  'right_eye_x': 917.0,
  'right_eye_y': 383.0,
  'left_eye_x': 1103.0,
  'left_eye_y': 386.0,
  'frame_idx': 12},
 {'bb_x': 796.0,
  'bb_y': 197.0,
  'bb_w': 398.0,
  'bb_h': 509.0,
  'right_eye_x': 917.0,
  'right_eye_y': 382.0,
  'left_eye_x': 1103.0,
  'left_eye_y': 385.0,
  'frame_idx': 13},
 {'bb_x': 795.0,
  'bb_y': 195.0,
  'bb_w': 400.0,
  'bb_h': 515.0,
  'right_eye_x': 917.0,
  'right_eye_y': 382.0,
  'left_eye_x': 1103.0,
  'left_eye_y': 385.0,
  'frame_idx': 14},
 {'bb_x': 794.0,
  'bb_y': 193.0,
  'bb_w': 402.0,
  'bb_h': 522.0,
  'right_eye_x': 917.0,
  'right_eye_y': 381.0,
  'left_eye_x': 1104.0,
  'left_eye_y': 385.0,
  'frame_idx': 15},
 {'bb_x': 793.0,
  'bb_y': 191.0,
  'bb_w': 404.0,
  'bb_h': 529.0,
  'right_eye_x': 916.0,
  'right_eye_y': 381.0,
  'left_eye_x': 1104.0,
  'left_eye_y': 384.0,
  'frame_idx': 16},
 {'bb_x': 792.0,
  'bb_y': 189.0,
  'bb_w': 406.0,
  'bb_h': 535.0,
  'right_eye_x': 916.0,
  'right_eye_y': 380.0,
  'left_eye_x': 1104.0,
  'left_eye_y': 384.0,
  'frame_idx': 17},
 {'bb_x': 791.0,
  'bb_y': 187.0,
  'bb_w': 408.0,
  'bb_h': 542.0,
  'right_eye_x': 916.0,
  'right_eye_y': 380.0,
  'left_eye_x': 1104.0,
  'left_eye_y': 383.0,
  'frame_idx': 18},
 {'bb_x': 790.0,
  'bb_y': 185.0,
  'bb_w': 410.0,
  'bb_h': 549.0,
  'right_eye_x': 916.0,
  'right_eye_y': 379.0,
  'left_eye_x': 1104.0,
  'left_eye_y': 383.0,
  'frame_idx': 19},
 {'bb_x': 789.0,
  'bb_y': 183.0,
  'bb_w': 413.0,
  'bb_h': 556.0,
  'right_eye_x': 916.0,
  'right_eye_y': 379.0,
  'left_eye_x': 1105.0,
  'left_eye_y': 383.0,
  'frame_idx': 20},
 {'bb_x': 788.0,
  'bb_y': 183.0,
  'bb_w': 411.0,
  'bb_h': 552.0,
  'right_eye_x': 915.0,
  'right_eye_y': 379.0,
  'left_eye_x': 1104.0,
  'left_eye_y': 383.0,
  'frame_idx': 21},
 {'bb_x': 788.0,
  'bb_y': 184.0,
  'bb_w': 409.0,
  'bb_h': 549.0,
  'right_eye_x': 915.0,
  'right_eye_y': 379.0,
  'left_eye_x': 1103.0,
  'left_eye_y': 383.0,
  'frame_idx': 22},
 {'bb_x': 788.0,
  'bb_y': 184.0,
  'bb_w': 407.0,
  'bb_h': 546.0,
  'right_eye_x': 914.0,
  'right_eye_y': 379.0,
  'left_eye_x': 1102.0,
  'left_eye_y': 383.0,
  'frame_idx': 23},
 {'bb_x': 787.0,
  'bb_y': 185.0,
  'bb_w': 405.0,
  'bb_h': 542.0,
  'right_eye_x': 914.0,
  'right_eye_y': 380.0,
  'left_eye_x': 1101.0,
  'left_eye_y': 384.0,
  'frame_idx': 24},
 {'bb_x': 787.0,
  'bb_y': 186.0,
  'bb_w': 403.0,
  'bb_h': 539.0,
  'right_eye_x': 913.0,
  'right_eye_y': 380.0,
  'left_eye_x': 1101.0,
  'left_eye_y': 384.0,
  'frame_idx': 25},
 {'bb_x': 787.0,
  'bb_y': 186.0,
  'bb_w': 401.0,
  'bb_h': 536.0,
  'right_eye_x': 913.0,
  'right_eye_y': 380.0,
  'left_eye_x': 1100.0,
  'left_eye_y': 384.0,
  'frame_idx': 26},
 {'bb_x': 786.0,
  'bb_y': 187.0,
  'bb_w': 399.0,
  'bb_h': 532.0,
  'right_eye_x': 912.0,
  'right_eye_y': 381.0,
  'left_eye_x': 1099.0,
  'left_eye_y': 385.0,
  'frame_idx': 27},
 {'bb_x': 786.0,
  'bb_y': 187.0,
  'bb_w': 397.0,
  'bb_h': 529.0,
  'right_eye_x': 912.0,
  'right_eye_y': 381.0,
  'left_eye_x': 1098.0,
  'left_eye_y': 385.0,
  'frame_idx': 28},
 {'bb_x': 786.0,
  'bb_y': 188.0,
  'bb_w': 395.0,
  'bb_h': 526.0,
  'right_eye_x': 911.0,
  'right_eye_y': 381.0,
  'left_eye_x': 1097.0,
  'left_eye_y': 385.0,
  'frame_idx': 29},
 {'bb_x': 786.0,
  'bb_y': 189.0,
  'bb_w': 394.0,
  'bb_h': 523.0,
  'right_eye_x': 911.0,
  'right_eye_y': 382.0,
  'left_eye_x': 1097.0,
  'left_eye_y': 386.0,
  'frame_idx': 30},
 {'bb_x': 786.0,
  'bb_y': 189.0,
  'bb_w': 394.0,
  'bb_h': 522.0,
  'right_eye_x': 911.0,
  'right_eye_y': 382.0,
  'left_eye_x': 1097.0,
  'left_eye_y': 386.0,
  'frame_idx': 31},
 {'bb_x': 786.0,
  'bb_y': 190.0,
  'bb_w': 395.0,
  'bb_h': 521.0,
  'right_eye_x': 912.0,
  'right_eye_y': 382.0,
  'left_eye_x': 1097.0,
  'left_eye_y': 386.0,
  'frame_idx': 32},
 {'bb_x': 786.0,
  'bb_y': 191.0,
  'bb_w': 395.0,
  'bb_h': 520.0,
  'right_eye_x': 912.0,
  'right_eye_y': 382.0,
  'left_eye_x': 1097.0,
  'left_eye_y': 386.0,
  'frame_idx': 33},
 {'bb_x': 787.0,
  'bb_y': 191.0,
  'bb_w': 396.0,
  'bb_h': 519.0,
  'right_eye_x': 913.0,
  'right_eye_y': 382.0,
  'left_eye_x': 1097.0,
  'left_eye_y': 387.0,
  'frame_idx': 34},
 {'bb_x': 787.0,
  'bb_y': 192.0,
  'bb_w': 396.0,
  'bb_h': 518.0,
  'right_eye_x': 913.0,
  'right_eye_y': 382.0,
  'left_eye_x': 1097.0,
  'left_eye_y': 387.0,
  'frame_idx': 35},
 {'bb_x': 787.0,
  'bb_y': 193.0,
  'bb_w': 397.0,
  'bb_h': 517.0,
  'right_eye_x': 914.0,
  'right_eye_y': 382.0,
  'left_eye_x': 1097.0,
  'left_eye_y': 387.0,
  'frame_idx': 36},
 {'bb_x': 788.0,
  'bb_y': 193.0,
  'bb_w': 397.0,
  'bb_h': 516.0,
  'right_eye_x': 914.0,
  'right_eye_y': 382.0,
  'left_eye_x': 1097.0,
  'left_eye_y': 388.0,
  'frame_idx': 37},
 {'bb_x': 788.0,
  'bb_y': 194.0,
  'bb_w': 398.0,
  'bb_h': 515.0,
  'right_eye_x': 915.0,
  'right_eye_y': 382.0,
  'left_eye_x': 1097.0,
  'left_eye_y': 388.0,
  'frame_idx': 38},
 {'bb_x': 788.0,
  'bb_y': 195.0,
  'bb_w': 398.0,
  'bb_h': 514.0,
  'right_eye_x': 915.0,
  'right_eye_y': 382.0,
  'left_eye_x': 1097.0,
  'left_eye_y': 388.0,
  'frame_idx': 39},
 {'bb_x': 789.0,
  'bb_y': 196.0,
  'bb_w': 399.0,
  'bb_h': 514.0,
  'right_eye_x': 916.0,
  'right_eye_y': 382.0,
  'left_eye_x': 1097.0,
  'left_eye_y': 389.0,
  'frame_idx': 40},
 {'bb_x': 788.0,
  'bb_y': 195.0,
  'bb_w': 399.0,
  'bb_h': 514.0,
  'right_eye_x': 915.0,
  'right_eye_y': 382.0,
  'left_eye_x': 1096.0,
  'left_eye_y': 389.0,
  'frame_idx': 41},
 {'bb_x': 788.0,
  'bb_y': 194.0,
  'bb_w': 399.0,
  'bb_h': 515.0,
  'right_eye_x': 915.0,
  'right_eye_y': 383.0,
  'left_eye_x': 1096.0,
  'left_eye_y': 389.0,
  'frame_idx': 42},
 {'bb_x': 787.0,
  'bb_y': 193.0,
  'bb_w': 399.0,
  'bb_h': 515.0,
  'right_eye_x': 914.0,
  'right_eye_y': 384.0,
  'left_eye_x': 1095.0,
  'left_eye_y': 389.0,
  'frame_idx': 43},
 {'bb_x': 787.0,
  'bb_y': 192.0,
  'bb_w': 399.0,
  'bb_h': 516.0,
  'right_eye_x': 914.0,
  'right_eye_y': 384.0,
  'left_eye_x': 1095.0,
  'left_eye_y': 389.0,
  'frame_idx': 44},
 {'bb_x': 787.0,
  'bb_y': 191.0,
  'bb_w': 399.0,
  'bb_h': 517.0,
  'right_eye_x': 914.0,
  'right_eye_y': 385.0,
  'left_eye_x': 1094.0,
  'left_eye_y': 390.0,
  'frame_idx': 45},
 {'bb_x': 786.0,
  'bb_y': 190.0,
  'bb_w': 399.0,
  'bb_h': 517.0,
  'right_eye_x': 913.0,
  'right_eye_y': 386.0,
  'left_eye_x': 1094.0,
  'left_eye_y': 390.0,
  'frame_idx': 46},
 {'bb_x': 786.0,
  'bb_y': 189.0,
  'bb_w': 399.0,
  'bb_h': 518.0,
  'right_eye_x': 913.0,
  'right_eye_y': 386.0,
  'left_eye_x': 1093.0,
  'left_eye_y': 390.0,
  'frame_idx': 47},
 {'bb_x': 785.0,
  'bb_y': 188.0,
  'bb_w': 399.0,
  'bb_h': 518.0,
  'right_eye_x': 912.0,
  'right_eye_y': 387.0,
  'left_eye_x': 1093.0,
  'left_eye_y': 390.0,
  'frame_idx': 48},
 {'bb_x': 785.0,
  'bb_y': 187.0,
  'bb_w': 399.0,
  'bb_h': 519.0,
  'right_eye_x': 912.0,
  'right_eye_y': 388.0,
  'left_eye_x': 1092.0,
  'left_eye_y': 390.0,
  'frame_idx': 49},
 {'bb_x': 785.0,
  'bb_y': 186.0,
  'bb_w': 400.0,
  'bb_h': 520.0,
  'right_eye_x': 912.0,
  'right_eye_y': 389.0,
  'left_eye_x': 1092.0,
  'left_eye_y': 391.0,
  'frame_idx': 50},
 {'bb_x': 787.0,
  'bb_y': 188.0,
  'bb_w': 399.0,
  'bb_h': 519.0,
  'right_eye_x': 914.0,
  'right_eye_y': 389.0,
  'left_eye_x': 1094.0,
  'left_eye_y': 391.0,
  'frame_idx': 51},
 {'bb_x': 790.0,
  'bb_y': 190.0,
  'bb_w': 399.0,
  'bb_h': 519.0,
  'right_eye_x': 917.0,
  'right_eye_y': 390.0,
  'left_eye_x': 1097.0,
  'left_eye_y': 392.0,
  'frame_idx': 52},
 {'bb_x': 793.0,
  'bb_y': 193.0,
  'bb_w': 398.0,
  'bb_h': 519.0,
  'right_eye_x': 919.0,
  'right_eye_y': 390.0,
  'left_eye_x': 1100.0,
  'left_eye_y': 393.0,
  'frame_idx': 53},
 {'bb_x': 796.0,
  'bb_y': 195.0,
  'bb_w': 398.0,
  'bb_h': 519.0,
  'right_eye_x': 922.0,
  'right_eye_y': 391.0,
  'left_eye_x': 1102.0,
  'left_eye_y': 394.0,
  'frame_idx': 54},
 {'bb_x': 799.0,
  'bb_y': 198.0,
  'bb_w': 398.0,
  'bb_h': 519.0,
  'right_eye_x': 925.0,
  'right_eye_y': 391.0,
  'left_eye_x': 1105.0,
  'left_eye_y': 395.0,
  'frame_idx': 55},
 {'bb_x': 801.0,
  'bb_y': 200.0,
  'bb_w': 397.0,
  'bb_h': 518.0,
  'right_eye_x': 927.0,
  'right_eye_y': 392.0,
  'left_eye_x': 1108.0,
  'left_eye_y': 395.0,
  'frame_idx': 56},
 {'bb_x': 804.0,
  'bb_y': 202.0,
  'bb_w': 397.0,
  'bb_h': 518.0,
  'right_eye_x': 930.0,
  'right_eye_y': 392.0,
  'left_eye_x': 1110.0,
  'left_eye_y': 396.0,
  'frame_idx': 57},
 {'bb_x': 807.0,
  'bb_y': 205.0,
  'bb_w': 396.0,
  'bb_h': 518.0,
  'right_eye_x': 932.0,
  'right_eye_y': 393.0,
  'left_eye_x': 1113.0,
  'left_eye_y': 397.0,
  'frame_idx': 58},
 {'bb_x': 810.0,
  'bb_y': 207.0,
  'bb_w': 396.0,
  'bb_h': 518.0,
  'right_eye_x': 935.0,
  'right_eye_y': 393.0,
  'left_eye_x': 1116.0,
  'left_eye_y': 398.0,
  'frame_idx': 59},
 {'bb_x': 813.0,
  'bb_y': 210.0,
  'bb_w': 396.0,
  'bb_h': 518.0,
  'right_eye_x': 938.0,
  'right_eye_y': 394.0,
  'left_eye_x': 1119.0,
  'left_eye_y': 399.0,
  'frame_idx': 60},
 {'bb_x': 813.0,
  'bb_y': 208.0,
  'bb_w': 396.0,
  'bb_h': 519.0,
  'right_eye_x': 940.0,
  'right_eye_y': 393.0,
  'left_eye_x': 1121.0,
  'left_eye_y': 398.0,
  'frame_idx': 61},
 {'bb_x': 814.0,
  'bb_y': 207.0,
  'bb_w': 396.0,
  'bb_h': 520.0,
  'right_eye_x': 943.0,
  'right_eye_y': 393.0,
  'left_eye_x': 1123.0,
  'left_eye_y': 398.0,
  'frame_idx': 62},
 {'bb_x': 815.0,
  'bb_y': 206.0,
  'bb_w': 396.0,
  'bb_h': 521.0,
  'right_eye_x': 946.0,
  'right_eye_y': 393.0,
  'left_eye_x': 1125.0,
  'left_eye_y': 398.0,
  'frame_idx': 63},
 {'bb_x': 815.0,
  'bb_y': 205.0,
  'bb_w': 396.0,
  'bb_h': 523.0,
  'right_eye_x': 949.0,
  'right_eye_y': 393.0,
  'left_eye_x': 1127.0,
  'left_eye_y': 398.0,
  'frame_idx': 64},
 {'bb_x': 816.0,
  'bb_y': 204.0,
  'bb_w': 397.0,
  'bb_h': 524.0,
  'right_eye_x': 952.0,
  'right_eye_y': 393.0,
  'left_eye_x': 1129.0,
  'left_eye_y': 398.0,
  'frame_idx': 65},
 {'bb_x': 817.0,
  'bb_y': 202.0,
  'bb_w': 397.0,
  'bb_h': 525.0,
  'right_eye_x': 955.0,
  'right_eye_y': 392.0,
  'left_eye_x': 1131.0,
  'left_eye_y': 398.0,
  'frame_idx': 66},
 {'bb_x': 817.0,
  'bb_y': 201.0,
  'bb_w': 397.0,
  'bb_h': 527.0,
  'right_eye_x': 958.0,
  'right_eye_y': 392.0,
  'left_eye_x': 1133.0,
  'left_eye_y': 398.0,
  'frame_idx': 67},
 {'bb_x': 818.0,
  'bb_y': 200.0,
  'bb_w': 397.0,
  'bb_h': 528.0,
  'right_eye_x': 961.0,
  'right_eye_y': 392.0,
  'left_eye_x': 1135.0,
  'left_eye_y': 398.0,
  'frame_idx': 68},
 {'bb_x': 819.0,
  'bb_y': 199.0,
  'bb_w': 397.0,
  'bb_h': 529.0,
  'right_eye_x': 964.0,
  'right_eye_y': 392.0,
  'left_eye_x': 1137.0,
  'left_eye_y': 398.0,
  'frame_idx': 69},
 {'bb_x': 820.0,
  'bb_y': 198.0,
  'bb_w': 398.0,
  'bb_h': 531.0,
  'right_eye_x': 967.0,
  'right_eye_y': 392.0,
  'left_eye_x': 1139.0,
  'left_eye_y': 398.0,
  'frame_idx': 70},
 {'bb_x': 818.0,
  'bb_y': 198.0,
  'bb_w': 398.0,
  'bb_h': 531.0,
  'right_eye_x': 965.0,
  'right_eye_y': 392.0,
  'left_eye_x': 1138.0,
  'left_eye_y': 398.0,
  'frame_idx': 71},
 {'bb_x': 816.0,
  'bb_y': 198.0,
  'bb_w': 399.0,
  'bb_h': 531.0,
  'right_eye_x': 964.0,
  'right_eye_y': 393.0,
  'left_eye_x': 1137.0,
  'left_eye_y': 399.0,
  'frame_idx': 72},
 {'bb_x': 814.0,
  'bb_y': 198.0,
  'bb_w': 400.0,
  'bb_h': 532.0,
  'right_eye_x': 962.0,
  'right_eye_y': 394.0,
  'left_eye_x': 1136.0,
  'left_eye_y': 400.0,
  'frame_idx': 73},
 {'bb_x': 813.0,
  'bb_y': 199.0,
  'bb_w': 400.0,
  'bb_h': 532.0,
  'right_eye_x': 961.0,
  'right_eye_y': 395.0,
  'left_eye_x': 1135.0,
  'left_eye_y': 401.0,
  'frame_idx': 74},
 {'bb_x': 811.0,
  'bb_y': 199.0,
  'bb_w': 401.0,
  'bb_h': 533.0,
  'right_eye_x': 960.0,
  'right_eye_y': 396.0,
  'left_eye_x': 1135.0,
  'left_eye_y': 402.0,
  'frame_idx': 75},
 {'bb_x': 809.0,
  'bb_y': 199.0,
  'bb_w': 402.0,
  'bb_h': 533.0,
  'right_eye_x': 958.0,
  'right_eye_y': 396.0,
  'left_eye_x': 1134.0,
  'left_eye_y': 402.0,
  'frame_idx': 76},
 {'bb_x': 808.0,
  'bb_y': 200.0,
  'bb_w': 402.0,
  'bb_h': 533.0,
  'right_eye_x': 957.0,
  'right_eye_y': 397.0,
  'left_eye_x': 1133.0,
  'left_eye_y': 403.0,
  'frame_idx': 77},
 {'bb_x': 806.0,
  'bb_y': 200.0,
  'bb_w': 403.0,
  'bb_h': 534.0,
  'right_eye_x': 955.0,
  'right_eye_y': 398.0,
  'left_eye_x': 1132.0,
  'left_eye_y': 404.0,
  'frame_idx': 78},
 {'bb_x': 804.0,
  'bb_y': 200.0,
  'bb_w': 404.0,
  'bb_h': 534.0,
  'right_eye_x': 954.0,
  'right_eye_y': 399.0,
  'left_eye_x': 1131.0,
  'left_eye_y': 405.0,
  'frame_idx': 79},
 {'bb_x': 803.0,
  'bb_y': 201.0,
  'bb_w': 405.0,
  'bb_h': 535.0,
  'right_eye_x': 953.0,
  'right_eye_y': 400.0,
  'left_eye_x': 1131.0,
  'left_eye_y': 406.0,
  'frame_idx': 80},
 {'bb_x': 803.0,
  'bb_y': 200.0,
  'bb_w': 403.0,
  'bb_h': 535.0,
  'right_eye_x': 949.0,
  'right_eye_y': 398.0,
  'left_eye_x': 1127.0,
  'left_eye_y': 405.0,
  'frame_idx': 81},
 {'bb_x': 804.0,
  'bb_y': 200.0,
  'bb_w': 402.0,
  'bb_h': 536.0,
  'right_eye_x': 945.0,
  'right_eye_y': 397.0,
  'left_eye_x': 1123.0,
  'left_eye_y': 404.0,
  'frame_idx': 82},
 {'bb_x': 804.0,
  'bb_y': 200.0,
  'bb_w': 400.0,
  'bb_h': 537.0,
  'right_eye_x': 941.0,
  'right_eye_y': 395.0,
  'left_eye_x': 1119.0,
  'left_eye_y': 403.0,
  'frame_idx': 83},
 {'bb_x': 805.0,
  'bb_y': 200.0,
  'bb_w': 399.0,
  'bb_h': 537.0,
  'right_eye_x': 938.0,
  'right_eye_y': 394.0,
  'left_eye_x': 1115.0,
  'left_eye_y': 402.0,
  'frame_idx': 84},
 {'bb_x': 806.0,
  'bb_y': 200.0,
  'bb_w': 397.0,
  'bb_h': 538.0,
  'right_eye_x': 934.0,
  'right_eye_y': 393.0,
  'left_eye_x': 1112.0,
  'left_eye_y': 401.0,
  'frame_idx': 85},
 {'bb_x': 806.0,
  'bb_y': 199.0,
  'bb_w': 396.0,
  'bb_h': 539.0,
  'right_eye_x': 930.0,
  'right_eye_y': 391.0,
  'left_eye_x': 1108.0,
  'left_eye_y': 400.0,
  'frame_idx': 86},
 {'bb_x': 807.0,
  'bb_y': 199.0,
  'bb_w': 394.0,
  'bb_h': 539.0,
  'right_eye_x': 927.0,
  'right_eye_y': 390.0,
  'left_eye_x': 1104.0,
  'left_eye_y': 399.0,
  'frame_idx': 87},
 {'bb_x': 807.0,
  'bb_y': 199.0,
  'bb_w': 393.0,
  'bb_h': 540.0,
  'right_eye_x': 923.0,
  'right_eye_y': 388.0,
  'left_eye_x': 1100.0,
  'left_eye_y': 398.0,
  'frame_idx': 88},
 {'bb_x': 808.0,
  'bb_y': 199.0,
  'bb_w': 391.0,
  'bb_h': 541.0,
  'right_eye_x': 919.0,
  'right_eye_y': 387.0,
  'left_eye_x': 1096.0,
  'left_eye_y': 397.0,
  'frame_idx': 89},
 {'bb_x': 809.0,
  'bb_y': 199.0,
  'bb_w': 390.0,
  'bb_h': 542.0,
  'right_eye_x': 916.0,
  'right_eye_y': 386.0,
  'left_eye_x': 1093.0,
  'left_eye_y': 396.0,
  'frame_idx': 90},
 {'bb_x': 809.0,
  'bb_y': 197.0,
  'bb_w': 390.0,
  'bb_h': 541.0,
  'right_eye_x': 915.0,
  'right_eye_y': 385.0,
  'left_eye_x': 1093.0,
  'left_eye_y': 395.0,
  'frame_idx': 91},
 {'bb_x': 810.0,
  'bb_y': 195.0,
  'bb_w': 390.0,
  'bb_h': 540.0,
  'right_eye_x': 914.0,
  'right_eye_y': 385.0,
  'left_eye_x': 1093.0,
  'left_eye_y': 394.0,
  'frame_idx': 92},
 {'bb_x': 811.0,
  'bb_y': 194.0,
  'bb_w': 390.0,
  'bb_h': 539.0,
  'right_eye_x': 913.0,
  'right_eye_y': 385.0,
  'left_eye_x': 1093.0,
  'left_eye_y': 394.0,
  'frame_idx': 93},
 {'bb_x': 811.0,
  'bb_y': 192.0,
  'bb_w': 391.0,
  'bb_h': 538.0,
  'right_eye_x': 913.0,
  'right_eye_y': 384.0,
  'left_eye_x': 1093.0,
  'left_eye_y': 393.0,
  'frame_idx': 94},
 {'bb_x': 812.0,
  'bb_y': 191.0,
  'bb_w': 391.0,
  'bb_h': 537.0,
  'right_eye_x': 912.0,
  'right_eye_y': 384.0,
  'left_eye_x': 1093.0,
  'left_eye_y': 393.0,
  'frame_idx': 95},
 {'bb_x': 813.0,
  'bb_y': 189.0,
  'bb_w': 391.0,
  'bb_h': 536.0,
  'right_eye_x': 911.0,
  'right_eye_y': 384.0,
  'left_eye_x': 1093.0,
  'left_eye_y': 392.0,
  'frame_idx': 96},
 {'bb_x': 813.0,
  'bb_y': 187.0,
  'bb_w': 392.0,
  'bb_h': 535.0,
  'right_eye_x': 911.0,
  'right_eye_y': 383.0,
  'left_eye_x': 1093.0,
  'left_eye_y': 391.0,
  'frame_idx': 97},
 {'bb_x': 814.0,
  'bb_y': 186.0,
  'bb_w': 392.0,
  'bb_h': 534.0,
  'right_eye_x': 910.0,
  'right_eye_y': 383.0,
  'left_eye_x': 1093.0,
  'left_eye_y': 391.0,
  'frame_idx': 98},
 {'bb_x': 815.0,
  'bb_y': 184.0,
  'bb_w': 392.0,
  'bb_h': 533.0,
  'right_eye_x': 909.0,
  'right_eye_y': 383.0,
  'left_eye_x': 1093.0,
  'left_eye_y': 390.0,
  'frame_idx': 99},
 {'bb_x': 816.0,
  'bb_y': 183.0,
  'bb_w': 393.0,
  'bb_h': 533.0,
  'right_eye_x': 909.0,
  'right_eye_y': 383.0,
  'left_eye_x': 1093.0,
  'left_eye_y': 390.0,
  'frame_idx': 100},
 {'bb_x': 814.0,
  'bb_y': 183.0,
  'bb_w': 394.0,
  'bb_h': 531.0,
  'right_eye_x': 911.0,
  'right_eye_y': 381.0,
  'left_eye_x': 1095.0,
  'left_eye_y': 388.0,
  'frame_idx': 101},
 {'bb_x': 812.0,
  'bb_y': 183.0,
  'bb_w': 395.0,
  'bb_h': 529.0,
  'right_eye_x': 914.0,
  'right_eye_y': 379.0,
  'left_eye_x': 1098.0,
  'left_eye_y': 386.0,
  'frame_idx': 102},
 {'bb_x': 810.0,
  'bb_y': 183.0,
  'bb_w': 396.0,
  'bb_h': 528.0,
  'right_eye_x': 917.0,
  'right_eye_y': 377.0,
  'left_eye_x': 1101.0,
  'left_eye_y': 385.0,
  'frame_idx': 103},
 {'bb_x': 808.0,
  'bb_y': 183.0,
  'bb_w': 397.0,
  'bb_h': 526.0,
  'right_eye_x': 920.0,
  'right_eye_y': 375.0,
  'left_eye_x': 1103.0,
  'left_eye_y': 383.0,
  'frame_idx': 104},
 {'bb_x': 806.0,
  'bb_y': 183.0,
  'bb_w': 398.0,
  'bb_h': 525.0,
  'right_eye_x': 923.0,
  'right_eye_y': 373.0,
  'left_eye_x': 1106.0,
  'left_eye_y': 382.0,
  'frame_idx': 105},
 {'bb_x': 804.0,
  'bb_y': 183.0,
  'bb_w': 399.0,
  'bb_h': 523.0,
  'right_eye_x': 926.0,
  'right_eye_y': 371.0,
  'left_eye_x': 1109.0,
  'left_eye_y': 380.0,
  'frame_idx': 106},
 {'bb_x': 802.0,
  'bb_y': 183.0,
  'bb_w': 400.0,
  'bb_h': 521.0,
  'right_eye_x': 929.0,
  'right_eye_y': 369.0,
  'left_eye_x': 1111.0,
  'left_eye_y': 378.0,
  'frame_idx': 107},
 {'bb_x': 800.0,
  'bb_y': 183.0,
  'bb_w': 401.0,
  'bb_h': 520.0,
  'right_eye_x': 932.0,
  'right_eye_y': 367.0,
  'left_eye_x': 1114.0,
  'left_eye_y': 377.0,
  'frame_idx': 108},
 {'bb_x': 798.0,
  'bb_y': 183.0,
  'bb_w': 402.0,

In [ ]:
# 11.7mb video 1080p MPEG-4 AAC, H.264, stereo, duration 21s
# bbox computed 1m13s
# frames_per_second=1 - 10.7s
# frames_per_second=3 - 24.5s
# frames_per_second=10 - 1m12s
# frames_per_second=15 - 1m49s
# frames_per_second=25 - 3m51s
# frames_per_second=30 - 3m33s

head_movement_df, summary_df = owf.head_movement(
    video_path="video.mov",
    frames_per_second=30,
    normalize_by_bb_size=False,
    bbox_list=bbox_list,
    padding_percent=0.1,
)

INFO:root:Loading Face model: retinaface
INFO:root:Loading Facial Landmark model: mobilefacenet
INFO:root:Loading facepose model: img2pose
INFO:root:Loading AU model: xgb
INFO:root:Loading emotion model: resmasknet
INFO:root:Loading Identity model: facenet
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:error processing frame: 251 in file: video.mov & Error: cannot convert float NaN to integer
INFO:root:error processing frame: 252 in file: video.mov & Error: cannot convert float NaN to integer
INFO:root:error processing frame: 253 in file: video.mov & Error: cannot convert float NaN to integer
INFO:root:error processing frame: 254 in file: video.mov & Error: cannot convert float NaN to integer
INFO:root:error processing frame: 255 in file: video.mov & Error: cannot convert float NaN to integer
INFO:root:error processing frame: 256 in file: video.mov & Error: cannot convert float NaN to integer
INFO:root:error processing frame: 257 in file: video.mov & Error: cannot convert float NaN to integer
INFO:root:error processing frame: 258 in file: video.mov & Error: cannot convert float NaN to integer
INFO:root:error processing frame: 259 in file: video.mov & Error: cannot convert float NaN to integer
INFO:root:error processing frame: 260 in file: video.mov & Error: cannot convert float NaN to integer
INFO:root:error processing frame: 261 in file: video.mov & Error: cannot convert float NaN to integer
INFO:root:error processing frame: 262 in file: video.mov & Error: cannot convert float NaN to integer
INFO:root:error processing frame: 263 in file: video.mov & Error: cannot convert float NaN to integer
INFO:root:error processing frame: 264 in file: video.mov & Error: cannot convert float NaN to integer
INFO:root:error processing frame: 265 in file: video.mov & Error: cannot convert float NaN to integer
INFO:root:error processing frame: 266 in file: video.mov & Error: cannot convert float NaN to integer
INFO:root:error processing frame: 267 in file: video.mov & Error: cannot convert float NaN to integer
INFO:root:error processing frame: 268 in file: video.mov & Error: cannot convert float NaN to integer
INFO:root:error processing frame: 269 in file: video.mov & Error: cannot convert float NaN to integer
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...

In [22]:
head_movement_df.head(10)

,frame,bb_x1,bb_y1,bb_x2,bb_y2,face_confidence,pitch,roll,yaw,time,bb_center_x,bb_center_y,euclidean_angle,euclidean_angle_disp,xy_disp
0,0.0,797.0,184.0,1201.0,697.0,1.0,2.110125,-2.437714,-4.652455,0.000000,999.0,440.5,5.696641,NaN,0.000000
1,1.0,797.0,186.0,1199.0,696.0,1.0,2.132645,-2.226711,-5.214525,0.033333,998.0,441.0,6.092844,0.396203,1.118034
2,2.0,797.0,188.0,1198.0,696.0,1.0,1.842919,-1.977180,-5.278443,0.066667,997.5,442.0,5.957998,0.134846,1.118034
3,3.0,797.0,190.0,1197.0,695.0,1.0,1.485637,-1.835710,-4.204793,0.100000,997.0,442.5,4.843004,1.114994,0.707107
4,4.0,798.0,192.0,1197.0,695.0,1.0,1.536854,-2.093985,-4.021600,0.133333,997.5,443.5,4.810697,0.032306,1.118034
5,5.0,798.0,194.0,1196.0,695.0,1.0,1.802960,-2.083352,-3.913797,0.166667,997.0,444.5,4.812702,0.002005,1.118034
6,6.0,798.0,196.0,1194.0,694.0,1.0,1.675508,-1.763643,-2.444208,0.200000,996.0,445.0,3.466534,1.346168,1.118034
7,7.0,799.0,198.0,1194.0,694.0,1.0,1.709699,-1.619238,-2.388087,0.233333,996.5,446.0,3.370809,0.095725,1.118034
8,8.0,799.0,200.0,1193.0,693.0,1.0,1.900287,-1.594543,-2.490543,0.266667,996.0,446.5,3.533691,0.162882,0.707107
9,9.0,799.0,202.0,1192.0,693.0,1.0,2.060759,-1.580433,-2.500955,0.300000,995.5,447.5,3.624926,0.091235,1.118034

In [21]:
summary_df

,xy_disp_mean,pitch_mean,yaw_mean,roll_mean,euclidean_angle_disp_mean,xy_disp_std,pitch_std,yaw_std,roll_std,euclidean_angle_disp_std
0,2.577598,-1.589564,-1.297964,2.629292,0.773047,2.727838,4.638861,3.077421,2.351195,0.841143

## other model

In [30]:
bb_dict, facedata_df = owf.preprocess_face_video(
    "video.mov",
    n_people=1,
    detector_backend="mediapipe",
    face_threshold=0.9,
)

bbox_list = bb_dict[0]
bbox_list

[{'bb_x': 800.0,
  'bb_y': 301.0,
  'bb_w': 419.0,
  'bb_h': 419.0,
  'right_eye_x': 915.0,
  'right_eye_y': 405.0,
  'left_eye_x': 1094.0,
  'left_eye_y': 397.0,
  'frame_idx': 0},
 {'bb_x': 800.0,
  'bb_y': 301.0,
  'bb_w': 417.0,
  'bb_h': 417.0,
  'right_eye_x': 915.0,
  'right_eye_y': 405.0,
  'left_eye_x': 1094.0,
  'left_eye_y': 398.0,
  'frame_idx': 1},
 {'bb_x': 800.0,
  'bb_y': 302.0,
  'bb_w': 416.0,
  'bb_h': 416.0,
  'right_eye_x': 916.0,
  'right_eye_y': 405.0,
  'left_eye_x': 1094.0,
  'left_eye_y': 399.0,
  'frame_idx': 2},
 {'bb_x': 800.0,
  'bb_y': 303.0,
  'bb_w': 414.0,
  'bb_h': 414.0,
  'right_eye_x': 917.0,
  'right_eye_y': 405.0,
  'left_eye_x': 1094.0,
  'left_eye_y': 400.0,
  'frame_idx': 3},
 {'bb_x': 800.0,
  'bb_y': 304.0,
  'bb_w': 413.0,
  'bb_h': 413.0,
  'right_eye_x': 917.0,
  'right_eye_y': 406.0,
  'left_eye_x': 1094.0,
  'left_eye_y': 401.0,
  'frame_idx': 4},
 {'bb_x': 800.0,
  'bb_y': 305.0,
  'bb_w': 411.0,
  'bb_h': 411.0,
  'right_eye_x': 918.0,
  'right_eye_y': 406.0,
  'left_eye_x': 1094.0,
  'left_eye_y': 402.0,
  'frame_idx': 5},
 {'bb_x': 800.0,
  'bb_y': 306.0,
  'bb_w': 410.0,
  'bb_h': 410.0,
  'right_eye_x': 919.0,
  'right_eye_y': 406.0,
  'left_eye_x': 1094.0,
  'left_eye_y': 403.0,
  'frame_idx': 6},
 {'bb_x': 800.0,
  'bb_y': 307.0,
  'bb_w': 408.0,
  'bb_h': 408.0,
  'right_eye_x': 919.0,
  'right_eye_y': 407.0,
  'left_eye_x': 1094.0,
  'left_eye_y': 404.0,
  'frame_idx': 7},
 {'bb_x': 800.0,
  'bb_y': 308.0,
  'bb_w': 407.0,
  'bb_h': 407.0,
  'right_eye_x': 920.0,
  'right_eye_y': 407.0,
  'left_eye_x': 1094.0,
  'left_eye_y': 405.0,
  'frame_idx': 8},
 {'bb_x': 800.0,
  'bb_y': 309.0,
  'bb_w': 405.0,
  'bb_h': 405.0,
  'right_eye_x': 921.0,
  'right_eye_y': 407.0,
  'left_eye_x': 1094.0,
  'left_eye_y': 406.0,
  'frame_idx': 9},
 {'bb_x': 800.0,
  'bb_y': 310.0,
  'bb_w': 404.0,
  'bb_h': 404.0,
  'right_eye_x': 922.0,
  'right_eye_y': 408.0,
  'left_eye_x': 1094.0,
  'left_eye_y': 407.0,
  'frame_idx': 10},
 {'bb_x': 799.0,
  'bb_y': 308.0,
  'bb_w': 407.0,
  'bb_h': 407.0,
  'right_eye_x': 921.0,
  'right_eye_y': 407.0,
  'left_eye_x': 1094.0,
  'left_eye_y': 406.0,
  'frame_idx': 11},
 {'bb_x': 798.0,
  'bb_y': 306.0,
  'bb_w': 411.0,
  'bb_h': 411.0,
  'right_eye_x': 921.0,
  'right_eye_y': 407.0,
  'left_eye_x': 1095.0,
  'left_eye_y': 405.0,
  'frame_idx': 12},
 {'bb_x': 797.0,
  'bb_y': 305.0,
  'bb_w': 415.0,
  'bb_h': 415.0,
  'right_eye_x': 921.0,
  'right_eye_y': 406.0,
  'left_eye_x': 1096.0,
  'left_eye_y': 404.0,
  'frame_idx': 13},
 {'bb_x': 796.0,
  'bb_y': 303.0,
  'bb_w': 418.0,
  'bb_h': 418.0,
  'right_eye_x': 921.0,
  'right_eye_y': 406.0,
  'left_eye_x': 1096.0,
  'left_eye_y': 403.0,
  'frame_idx': 14},
 {'bb_x': 796.0,
  'bb_y': 302.0,
  'bb_w': 422.0,
  'bb_h': 422.0,
  'right_eye_x': 921.0,
  'right_eye_y': 406.0,
  'left_eye_x': 1097.0,
  'left_eye_y': 402.0,
  'frame_idx': 15},
 {'bb_x': 795.0,
  'bb_y': 300.0,
  'bb_w': 426.0,
  'bb_h': 426.0,
  'right_eye_x': 920.0,
  'right_eye_y': 405.0,
  'left_eye_x': 1098.0,
  'left_eye_y': 401.0,
  'frame_idx': 16},
 {'bb_x': 794.0,
  'bb_y': 298.0,
  'bb_w': 429.0,
  'bb_h': 429.0,
  'right_eye_x': 920.0,
  'right_eye_y': 405.0,
  'left_eye_x': 1098.0,
  'left_eye_y': 400.0,
  'frame_idx': 17},
 {'bb_x': 793.0,
  'bb_y': 297.0,
  'bb_w': 433.0,
  'bb_h': 433.0,
  'right_eye_x': 920.0,
  'right_eye_y': 404.0,
  'left_eye_x': 1099.0,
  'left_eye_y': 399.0,
  'frame_idx': 18},
 {'bb_x': 792.0,
  'bb_y': 295.0,
  'bb_w': 437.0,
  'bb_h': 437.0,
  'right_eye_x': 920.0,
  'right_eye_y': 404.0,
  'left_eye_x': 1100.0,
  'left_eye_y': 398.0,
  'frame_idx': 19},
 {'bb_x': 792.0,
  'bb_y': 294.0,
  'bb_w': 441.0,
  'bb_h': 441.0,
  'right_eye_x': 920.0,
  'right_eye_y': 404.0,
  'left_eye_x': 1101.0,
  'left_eye_y': 398.0,
  'frame_idx': 20},
 {'bb_x': 789.0,
  'bb_y': 292.0,
  'bb_w': 441.0,
  'bb_h': 441.0,
  'right_eye_x': 919.0,
  'right_eye_y': 403.0,
  'left_eye_x': 1100.0,
  'left_eye_y': 398.0,
  'frame_idx': 21},
 {'bb_x': 787.0,
  'bb_y': 290.0,
  'bb_w': 441.0,
  'bb_h': 441.0,
  'right_eye_x': 919.0,
  'right_eye_y': 402.0,
  'left_eye_x': 1099.0,
  'left_eye_y': 398.0,
  'frame_idx': 22},
 {'bb_x': 785.0,
  'bb_y': 288.0,
  'bb_w': 441.0,
  'bb_h': 441.0,
  'right_eye_x': 919.0,
  'right_eye_y': 402.0,
  'left_eye_x': 1099.0,
  'left_eye_y': 399.0,
  'frame_idx': 23},
 {'bb_x': 782.0,
  'bb_y': 287.0,
  'bb_w': 441.0,
  'bb_h': 441.0,
  'right_eye_x': 918.0,
  'right_eye_y': 401.0,
  'left_eye_x': 1098.0,
  'left_eye_y': 399.0,
  'frame_idx': 24},
 {'bb_x': 780.0,
  'bb_y': 285.0,
  'bb_w': 442.0,
  'bb_h': 442.0,
  'right_eye_x': 918.0,
  'right_eye_y': 401.0,
  'left_eye_x': 1098.0,
  'left_eye_y': 400.0,
  'frame_idx': 25},
 {'bb_x': 778.0,
  'bb_y': 283.0,
  'bb_w': 442.0,
  'bb_h': 442.0,
  'right_eye_x': 918.0,
  'right_eye_y': 400.0,
  'left_eye_x': 1097.0,
  'left_eye_y': 400.0,
  'frame_idx': 26},
 {'bb_x': 775.0,
  'bb_y': 282.0,
  'bb_w': 442.0,
  'bb_h': 442.0,
  'right_eye_x': 917.0,
  'right_eye_y': 399.0,
  'left_eye_x': 1096.0,
  'left_eye_y': 400.0,
  'frame_idx': 27},
 {'bb_x': 773.0,
  'bb_y': 280.0,
  'bb_w': 442.0,
  'bb_h': 442.0,
  'right_eye_x': 917.0,
  'right_eye_y': 399.0,
  'left_eye_x': 1096.0,
  'left_eye_y': 401.0,
  'frame_idx': 28},
 {'bb_x': 771.0,
  'bb_y': 278.0,
  'bb_w': 442.0,
  'bb_h': 442.0,
  'right_eye_x': 917.0,
  'right_eye_y': 398.0,
  'left_eye_x': 1095.0,
  'left_eye_y': 401.0,
  'frame_idx': 29},
 {'bb_x': 769.0,
  'bb_y': 277.0,
  'bb_w': 443.0,
  'bb_h': 443.0,
  'right_eye_x': 917.0,
  'right_eye_y': 398.0,
  'left_eye_x': 1095.0,
  'left_eye_y': 402.0,
  'frame_idx': 30},
 {'bb_x': 771.0,
  'bb_y': 278.0,
  'bb_w': 440.0,
  'bb_h': 440.0,
  'right_eye_x': 916.0,
  'right_eye_y': 399.0,
  'left_eye_x': 1094.0,
  'left_eye_y': 402.0,
  'frame_idx': 31},
 {'bb_x': 774.0,
  'bb_y': 280.0,
  'bb_w': 438.0,
  'bb_h': 438.0,
  'right_eye_x': 916.0,
  'right_eye_y': 400.0,
  'left_eye_x': 1094.0,
  'left_eye_y': 403.0,
  'frame_idx': 32},
 {'bb_x': 776.0,
  'bb_y': 282.0,
  'bb_w': 436.0,
  'bb_h': 436.0,
  'right_eye_x': 916.0,
  'right_eye_y': 401.0,
  'left_eye_x': 1093.0,
  'left_eye_y': 403.0,
  'frame_idx': 33},
 {'bb_x': 779.0,
  'bb_y': 284.0,
  'bb_w': 434.0,
  'bb_h': 434.0,
  'right_eye_x': 916.0,
  'right_eye_y': 402.0,
  'left_eye_x': 1093.0,
  'left_eye_y': 404.0,
  'frame_idx': 34},
 {'bb_x': 781.0,
  'bb_y': 286.0,
  'bb_w': 432.0,
  'bb_h': 432.0,
  'right_eye_x': 916.0,
  'right_eye_y': 403.0,
  'left_eye_x': 1093.0,
  'left_eye_y': 405.0,
  'frame_idx': 35},
 {'bb_x': 784.0,
  'bb_y': 288.0,
  'bb_w': 430.0,
  'bb_h': 430.0,
  'right_eye_x': 916.0,
  'right_eye_y': 404.0,
  'left_eye_x': 1092.0,
  'left_eye_y': 405.0,
  'frame_idx': 36},
 {'bb_x': 786.0,
  'bb_y': 290.0,
  'bb_w': 428.0,
  'bb_h': 428.0,
  'right_eye_x': 916.0,
  'right_eye_y': 405.0,
  'left_eye_x': 1092.0,
  'left_eye_y': 406.0,
  'frame_idx': 37},
 {'bb_x': 789.0,
  'bb_y': 292.0,
  'bb_w': 426.0,
  'bb_h': 426.0,
  'right_eye_x': 916.0,
  'right_eye_y': 406.0,
  'left_eye_x': 1091.0,
  'left_eye_y': 406.0,
  'frame_idx': 38},
 {'bb_x': 791.0,
  'bb_y': 294.0,
  'bb_w': 424.0,
  'bb_h': 424.0,
  'right_eye_x': 916.0,
  'right_eye_y': 407.0,
  'left_eye_x': 1091.0,
  'left_eye_y': 407.0,
  'frame_idx': 39},
 {'bb_x': 794.0,
  'bb_y': 296.0,
  'bb_w': 422.0,
  'bb_h': 422.0,
  'right_eye_x': 916.0,
  'right_eye_y': 409.0,
  'left_eye_x': 1091.0,
  'left_eye_y': 408.0,
  'frame_idx': 40},
 {'bb_x': 792.0,
  'bb_y': 295.0,
  'bb_w': 422.0,
  'bb_h': 422.0,
  'right_eye_x': 915.0,
  'right_eye_y': 408.0,
  'left_eye_x': 1091.0,
  'left_eye_y': 407.0,
  'frame_idx': 41},
 {'bb_x': 791.0,
  'bb_y': 294.0,
  'bb_w': 423.0,
  'bb_h': 423.0,
  'right_eye_x': 915.0,
  'right_eye_y': 408.0,
  'left_eye_x': 1091.0,
  'left_eye_y': 407.0,
  'frame_idx': 42},
 {'bb_x': 790.0,
  'bb_y': 293.0,
  'bb_w': 424.0,
  'bb_h': 424.0,
  'right_eye_x': 915.0,
  'right_eye_y': 408.0,
  'left_eye_x': 1092.0,
  'left_eye_y': 406.0,
  'frame_idx': 43},
 {'bb_x': 789.0,
  'bb_y': 293.0,
  'bb_w': 425.0,
  'bb_h': 425.0,
  'right_eye_x': 914.0,
  'right_eye_y': 407.0,
  'left_eye_x': 1092.0,
  'left_eye_y': 406.0,
  'frame_idx': 44},
 {'bb_x': 788.0,
  'bb_y': 292.0,
  'bb_w': 426.0,
  'bb_h': 426.0,
  'right_eye_x': 914.0,
  'right_eye_y': 407.0,
  'left_eye_x': 1093.0,
  'left_eye_y': 405.0,
  'frame_idx': 45},
 {'bb_x': 787.0,
  'bb_y': 291.0,
  'bb_w': 427.0,
  'bb_h': 427.0,
  'right_eye_x': 914.0,
  'right_eye_y': 407.0,
  'left_eye_x': 1093.0,
  'left_eye_y': 405.0,
  'frame_idx': 46},
 {'bb_x': 786.0,
  'bb_y': 291.0,
  'bb_w': 428.0,
  'bb_h': 428.0,
  'right_eye_x': 913.0,
  'right_eye_y': 406.0,
  'left_eye_x': 1093.0,
  'left_eye_y': 404.0,
  'frame_idx': 47},
 {'bb_x': 785.0,
  'bb_y': 290.0,
  'bb_w': 429.0,
  'bb_h': 429.0,
  'right_eye_x': 913.0,
  'right_eye_y': 406.0,
  'left_eye_x': 1094.0,
  'left_eye_y': 404.0,
  'frame_idx': 48},
 {'bb_x': 784.0,
  'bb_y': 289.0,
  'bb_w': 430.0,
  'bb_h': 430.0,
  'right_eye_x': 913.0,
  'right_eye_y': 406.0,
  'left_eye_x': 1094.0,
  'left_eye_y': 403.0,
  'frame_idx': 49},
 {'bb_x': 783.0,
  'bb_y': 289.0,
  'bb_w': 431.0,
  'bb_h': 431.0,
  'right_eye_x': 913.0,
  'right_eye_y': 406.0,
  'left_eye_x': 1095.0,
  'left_eye_y': 403.0,
  'frame_idx': 50},
 {'bb_x': 784.0,
  'bb_y': 291.0,
  'bb_w': 430.0,
  'bb_h': 430.0,
  'right_eye_x': 916.0,
  'right_eye_y': 406.0,
  'left_eye_x': 1097.0,
  'left_eye_y': 404.0,
  'frame_idx': 51},
 {'bb_x': 785.0,
  'bb_y': 293.0,
  'bb_w': 430.0,
  'bb_h': 430.0,
  'right_eye_x': 919.0,
  'right_eye_y': 407.0,
  'left_eye_x': 1100.0,
  'left_eye_y': 405.0,
  'frame_idx': 52},
 {'bb_x': 786.0,
  'bb_y': 295.0,
  'bb_w': 429.0,
  'bb_h': 429.0,
  'right_eye_x': 922.0,
  'right_eye_y': 408.0,
  'left_eye_x': 1102.0,
  'left_eye_y': 407.0,
  'frame_idx': 53},
 {'bb_x': 788.0,
  'bb_y': 298.0,
  'bb_w': 429.0,
  'bb_h': 429.0,
  'right_eye_x': 925.0,
  'right_eye_y': 408.0,
  'left_eye_x': 1105.0,
  'left_eye_y': 408.0,
  'frame_idx': 54},
 {'bb_x': 789.0,
  'bb_y': 300.0,
  'bb_w': 428.0,
  'bb_h': 428.0,
  'right_eye_x': 929.0,
  'right_eye_y': 409.0,
  'left_eye_x': 1108.0,
  'left_eye_y': 410.0,
  'frame_idx': 55},
 {'bb_x': 790.0,
  'bb_y': 302.0,
  'bb_w': 428.0,
  'bb_h': 428.0,
  'right_eye_x': 932.0,
  'right_eye_y': 410.0,
  'left_eye_x': 1110.0,
  'left_eye_y': 411.0,
  'frame_idx': 56},
 {'bb_x': 792.0,
  'bb_y': 305.0,
  'bb_w': 427.0,
  'bb_h': 427.0,
  'right_eye_x': 935.0,
  'right_eye_y': 410.0,
  'left_eye_x': 1113.0,
  'left_eye_y': 412.0,
  'frame_idx': 57},
 {'bb_x': 793.0,
  'bb_y': 307.0,
  'bb_w': 427.0,
  'bb_h': 427.0,
  'right_eye_x': 938.0,
  'right_eye_y': 411.0,
  'left_eye_x': 1115.0,
  'left_eye_y': 414.0,
  'frame_idx': 58},
 {'bb_x': 794.0,
  'bb_y': 309.0,
  'bb_w': 426.0,
  'bb_h': 426.0,
  'right_eye_x': 941.0,
  'right_eye_y': 412.0,
  'left_eye_x': 1118.0,
  'left_eye_y': 415.0,
  'frame_idx': 59},
 {'bb_x': 796.0,
  'bb_y': 312.0,
  'bb_w': 426.0,
  'bb_h': 426.0,
  'right_eye_x': 945.0,
  'right_eye_y': 413.0,
  'left_eye_x': 1121.0,
  'left_eye_y': 417.0,
  'frame_idx': 60},
 {'bb_x': 796.0,
  'bb_y': 312.0,
  'bb_w': 424.0,
  'bb_h': 424.0,
  'right_eye_x': 947.0,
  'right_eye_y': 412.0,
  'left_eye_x': 1122.0,
  'left_eye_y': 416.0,
  'frame_idx': 61},
 {'bb_x': 797.0,
  'bb_y': 312.0,
  'bb_w': 422.0,
  'bb_h': 422.0,
  'right_eye_x': 950.0,
  'right_eye_y': 412.0,
  'left_eye_x': 1124.0,
  'left_eye_y': 416.0,
  'frame_idx': 62},
 {'bb_x': 798.0,
  'bb_y': 312.0,
  'bb_w': 420.0,
  'bb_h': 420.0,
  'right_eye_x': 952.0,
  'right_eye_y': 411.0,
  'left_eye_x': 1126.0,
  'left_eye_y': 415.0,
  'frame_idx': 63},
 {'bb_x': 799.0,
  'bb_y': 312.0,
  'bb_w': 418.0,
  'bb_h': 418.0,
  'right_eye_x': 955.0,
  'right_eye_y': 411.0,
  'left_eye_x': 1128.0,
  'left_eye_y': 415.0,
  'frame_idx': 64},
 {'bb_x': 800.0,
  'bb_y': 313.0,
  'bb_w': 417.0,
  'bb_h': 417.0,
  'right_eye_x': 958.0,
  'right_eye_y': 410.0,
  'left_eye_x': 1130.0,
  'left_eye_y': 414.0,
  'frame_idx': 65},
 {'bb_x': 800.0,
  'bb_y': 313.0,
  'bb_w': 415.0,
  'bb_h': 415.0,
  'right_eye_x': 960.0,
  'right_eye_y': 410.0,
  'left_eye_x': 1131.0,
  'left_eye_y': 414.0,
  'frame_idx': 66},
 {'bb_x': 801.0,
  'bb_y': 313.0,
  'bb_w': 413.0,
  'bb_h': 413.0,
  'right_eye_x': 963.0,
  'right_eye_y': 409.0,
  'left_eye_x': 1133.0,
  'left_eye_y': 413.0,
  'frame_idx': 67},
 {'bb_x': 802.0,
  'bb_y': 313.0,
  'bb_w': 411.0,
  'bb_h': 411.0,
  'right_eye_x': 965.0,
  'right_eye_y': 409.0,
  'left_eye_x': 1135.0,
  'left_eye_y': 413.0,
  'frame_idx': 68},
 {'bb_x': 803.0,
  'bb_y': 313.0,
  'bb_w': 409.0,
  'bb_h': 409.0,
  'right_eye_x': 968.0,
  'right_eye_y': 408.0,
  'left_eye_x': 1137.0,
  'left_eye_y': 412.0,
  'frame_idx': 69},
 {'bb_x': 804.0,
  'bb_y': 314.0,
  'bb_w': 408.0,
  'bb_h': 408.0,
  'right_eye_x': 971.0,
  'right_eye_y': 408.0,
  'left_eye_x': 1139.0,
  'left_eye_y': 412.0,
  'frame_idx': 70},
 {'bb_x': 803.0,
  'bb_y': 314.0,
  'bb_w': 408.0,
  'bb_h': 408.0,
  'right_eye_x': 970.0,
  'right_eye_y': 408.0,
  'left_eye_x': 1138.0,
  'left_eye_y': 412.0,
  'frame_idx': 71},
 {'bb_x': 803.0,
  'bb_y': 314.0,
  'bb_w': 409.0,
  'bb_h': 409.0,
  'right_eye_x': 969.0,
  'right_eye_y': 408.0,
  'left_eye_x': 1138.0,
  'left_eye_y': 413.0,
  'frame_idx': 72},
 {'bb_x': 802.0,
  'bb_y': 314.0,
  'bb_w': 409.0,
  'bb_h': 409.0,
  'right_eye_x': 969.0,
  'right_eye_y': 408.0,
  'left_eye_x': 1138.0,
  'left_eye_y': 414.0,
  'frame_idx': 73},
 {'bb_x': 802.0,
  'bb_y': 315.0,
  'bb_w': 410.0,
  'bb_h': 410.0,
  'right_eye_x': 968.0,
  'right_eye_y': 408.0,
  'left_eye_x': 1137.0,
  'left_eye_y': 415.0,
  'frame_idx': 74},
 {'bb_x': 802.0,
  'bb_y': 315.0,
  'bb_w': 411.0,
  'bb_h': 411.0,
  'right_eye_x': 968.0,
  'right_eye_y': 409.0,
  'left_eye_x': 1137.0,
  'left_eye_y': 416.0,
  'frame_idx': 75},
 {'bb_x': 801.0,
  'bb_y': 315.0,
  'bb_w': 411.0,
  'bb_h': 411.0,
  'right_eye_x': 967.0,
  'right_eye_y': 409.0,
  'left_eye_x': 1137.0,
  'left_eye_y': 417.0,
  'frame_idx': 76},
 {'bb_x': 801.0,
  'bb_y': 316.0,
  'bb_w': 412.0,
  'bb_h': 412.0,
  'right_eye_x': 966.0,
  'right_eye_y': 409.0,
  'left_eye_x': 1136.0,
  'left_eye_y': 418.0,
  'frame_idx': 77},
 {'bb_x': 800.0,
  'bb_y': 316.0,
  'bb_w': 412.0,
  'bb_h': 412.0,
  'right_eye_x': 966.0,
  'right_eye_y': 409.0,
  'left_eye_x': 1136.0,
  'left_eye_y': 419.0,
  'frame_idx': 78},
 {'bb_x': 800.0,
  'bb_y': 316.0,
  'bb_w': 413.0,
  'bb_h': 413.0,
  'right_eye_x': 965.0,
  'right_eye_y': 409.0,
  'left_eye_x': 1136.0,
  'left_eye_y': 420.0,
  'frame_idx': 79},
 {'bb_x': 800.0,
  'bb_y': 317.0,
  'bb_w': 414.0,
  'bb_h': 414.0,
  'right_eye_x': 965.0,
  'right_eye_y': 410.0,
  'left_eye_x': 1136.0,
  'left_eye_y': 421.0,
  'frame_idx': 80},
 {'bb_x': 799.0,
  'bb_y': 314.0,
  'bb_w': 417.0,
  'bb_h': 417.0,
  'right_eye_x': 959.0,
  'right_eye_y': 410.0,
  'left_eye_x': 1130.0,
  'left_eye_y': 419.0,
  'frame_idx': 81},
 {'bb_x': 798.0,
  'bb_y': 312.0,
  'bb_w': 420.0,
  'bb_h': 420.0,
  'right_eye_x': 953.0,
  'right_eye_y': 411.0,
  'left_eye_x': 1125.0,
  'left_eye_y': 418.0,
  'frame_idx': 82},
 {'bb_x': 797.0,
  'bb_y': 310.0,
  'bb_w': 423.0,
  'bb_h': 423.0,
  'right_eye_x': 947.0,
  'right_eye_y': 411.0,
  'left_eye_x': 1120.0,
  'left_eye_y': 416.0,
  'frame_idx': 83},
 {'bb_x': 797.0,
  'bb_y': 308.0,
  'bb_w': 426.0,
  'bb_h': 426.0,
  'right_eye_x': 941.0,
  'right_eye_y': 412.0,
  'left_eye_x': 1115.0,
  'left_eye_y': 415.0,
  'frame_idx': 84},
 {'bb_x': 796.0,
  'bb_y': 306.0,
  'bb_w': 429.0,
  'bb_h': 429.0,
  'right_eye_x': 935.0,
  'right_eye_y': 413.0,
  'left_eye_x': 1110.0,
  'left_eye_y': 414.0,
  'frame_idx': 85},
 {'bb_x': 795.0,
  'bb_y': 303.0,
  'bb_w': 432.0,
  'bb_h': 432.0,
  'right_eye_x': 929.0,
  'right_eye_y': 413.0,
  'left_eye_x': 1105.0,
  'left_eye_y': 412.0,
  'frame_idx': 86},
 {'bb_x': 795.0,
  'bb_y': 301.0,
  'bb_w': 435.0,
  'bb_h': 435.0,
  'right_eye_x': 923.0,
  'right_eye_y': 414.0,
  'left_eye_x': 1100.0,
  'left_eye_y': 411.0,
  'frame_idx': 87},
 {'bb_x': 794.0,
  'bb_y': 299.0,
  'bb_w': 438.0,
  'bb_h': 438.0,
  'right_eye_x': 917.0,
  'right_eye_y': 414.0,
  'left_eye_x': 1095.0,
  'left_eye_y': 409.0,
  'frame_idx': 88},
 {'bb_x': 793.0,
  'bb_y': 297.0,
  'bb_w': 441.0,
  'bb_h': 441.0,
  'right_eye_x': 911.0,
  'right_eye_y': 415.0,
  'left_eye_x': 1090.0,
  'left_eye_y': 408.0,
  'frame_idx': 89},
 {'bb_x': 793.0,
  'bb_y': 295.0,
  'bb_w': 444.0,
  'bb_h': 444.0,
  'right_eye_x': 905.0,
  'right_eye_y': 416.0,
  'left_eye_x': 1085.0,
  'left_eye_y': 407.0,
  'frame_idx': 90},
 {'bb_x': 793.0,
  'bb_y': 294.0,
  'bb_w': 443.0,
  'bb_h': 443.0,
  'right_eye_x': 904.0,
  'right_eye_y': 415.0,
  'left_eye_x': 1085.0,
  'left_eye_y': 406.0,
  'frame_idx': 91},
 {'bb_x': 793.0,
  'bb_y': 293.0,
  'bb_w': 443.0,
  'bb_h': 443.0,
  'right_eye_x': 904.0,
  'right_eye_y': 414.0,
  'left_eye_x': 1085.0,
  'left_eye_y': 406.0,
  'frame_idx': 92},
 {'bb_x': 793.0,
  'bb_y': 293.0,
  'bb_w': 443.0,
  'bb_h': 443.0,
  'right_eye_x': 904.0,
  'right_eye_y': 414.0,
  'left_eye_x': 1085.0,
  'left_eye_y': 405.0,
  'frame_idx': 93},
 {'bb_x': 793.0,
  'bb_y': 292.0,
  'bb_w': 443.0,
  'bb_h': 443.0,
  'right_eye_x': 904.0,
  'right_eye_y': 413.0,
  'left_eye_x': 1085.0,
  'left_eye_y': 405.0,
  'frame_idx': 94},
 {'bb_x': 793.0,
  'bb_y': 292.0,
  'bb_w': 443.0,
  'bb_h': 443.0,
  'right_eye_x': 904.0,
  'right_eye_y': 413.0,
  'left_eye_x': 1085.0,
  'left_eye_y': 405.0,
  'frame_idx': 95},
 {'bb_x': 793.0,
  'bb_y': 291.0,
  'bb_w': 443.0,
  'bb_h': 443.0,
  'right_eye_x': 904.0,
  'right_eye_y': 412.0,
  'left_eye_x': 1085.0,
  'left_eye_y': 404.0,
  'frame_idx': 96},
 {'bb_x': 793.0,
  'bb_y': 290.0,
  'bb_w': 443.0,
  'bb_h': 443.0,
  'right_eye_x': 904.0,
  'right_eye_y': 411.0,
  'left_eye_x': 1085.0,
  'left_eye_y': 404.0,
  'frame_idx': 97},
 {'bb_x': 793.0,
  'bb_y': 290.0,
  'bb_w': 443.0,
  'bb_h': 443.0,
  'right_eye_x': 904.0,
  'right_eye_y': 411.0,
  'left_eye_x': 1085.0,
  'left_eye_y': 403.0,
  'frame_idx': 98},
 {'bb_x': 793.0,
  'bb_y': 289.0,
  'bb_w': 443.0,
  'bb_h': 443.0,
  'right_eye_x': 904.0,
  'right_eye_y': 410.0,
  'left_eye_x': 1085.0,
  'left_eye_y': 403.0,
  'frame_idx': 99},
 {'bb_x': 793.0,
  'bb_y': 289.0,
  'bb_w': 443.0,
  'bb_h': 443.0,
  'right_eye_x': 904.0,
  'right_eye_y': 410.0,
  'left_eye_x': 1085.0,
  'left_eye_y': 403.0,
  'frame_idx': 100},
 {'bb_x': 796.0,
  'bb_y': 290.0,
  'bb_w': 436.0,
  'bb_h': 436.0,
  'right_eye_x': 908.0,
  'right_eye_y': 408.0,
  'left_eye_x': 1087.0,
  'left_eye_y': 401.0,
  'frame_idx': 101},
 {'bb_x': 799.0,
  'bb_y': 292.0,
  'bb_w': 430.0,
  'bb_h': 430.0,
  'right_eye_x': 912.0,
  'right_eye_y': 406.0,
  'left_eye_x': 1090.0,
  'left_eye_y': 400.0,
  'frame_idx': 102},
 {'bb_x': 802.0,
  'bb_y': 294.0,
  'bb_w': 424.0,
  'bb_h': 424.0,
  'right_eye_x': 916.0,
  'right_eye_y': 405.0,
  'left_eye_x': 1093.0,
  'left_eye_y': 399.0,
  'frame_idx': 103},
 {'bb_x': 806.0,
  'bb_y': 295.0,
  'bb_w': 418.0,
  'bb_h': 418.0,
  'right_eye_x': 920.0,
  'right_eye_y': 403.0,
  'left_eye_x': 1095.0,
  'left_eye_y': 398.0,
  'frame_idx': 104},
 {'bb_x': 809.0,
  'bb_y': 297.0,
  'bb_w': 412.0,
  'bb_h': 412.0,
  'right_eye_x': 924.0,
  'right_eye_y': 402.0,
  'left_eye_x': 1098.0,
  'left_eye_y': 397.0,
  'frame_idx': 105},
 {'bb_x': 812.0,
  'bb_y': 299.0,
  'bb_w': 405.0,
  'bb_h': 405.0,
  'right_eye_x': 928.0,
  'right_eye_y': 400.0,
  'left_eye_x': 1101.0,
  'left_eye_y': 395.0,
  'frame_idx': 106},
 {'bb_x': 816.0,
  'bb_y': 300.0,
  'bb_w': 399.0,
  'bb_h': 399.0,
  'right_eye_x': 932.0,
  'right_eye_y': 398.0,
  'left_eye_x': 1103.0,
  'left_eye_y': 394.0,
  'frame_idx': 107},
 {'bb_x': 819.0,
  'bb_y': 302.0,
  'bb_w': 393.0,
  'bb_h': 393.0,
  'right_eye_x': 936.0,
  'right_eye_y': 397.0,
  'left_eye_x': 1106.0,
  'left_eye_y': 393.0,
  'frame_idx': 108},
 {'bb_x': 822.0,
  'bb_y': 304.0,
  'bb_w': 387.0,

In [ ]:
# bbox computed 8s
# frames_per_second=1 - 11s
# frames_per_second=3 - 25.4s
# frames_per_second=10 - 1m19s
# frames_per_second=15 - 1m57s
# frames_per_second=25 - 3m38.6s
# frames_per_second=30 - 3m45.5s
head_movement_df, summary_df = owf.head_movement(
    video_path="video.mov",
    frames_per_second=30,
    normalize_by_bb_size=False,
    bbox_list=bbox_list,
    padding_percent=0.1,
)

INFO:root:Loading Face model: retinaface
INFO:root:Loading Facial Landmark model: mobilefacenet
INFO:root:Loading facepose model: img2pose
INFO:root:Loading AU model: xgb
INFO:root:Loading emotion model: resmasknet
INFO:root:Loading Identity model: facenet
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:detecting poses...
INFO:root:error processing frame: 641 in file: video.mov & Error: cannot convert float NaN to integer
INFO:root:error processing frame: 642 in file: video.mov & Error: cannot convert float NaN to integer
INFO:root:error processing frame: 643 in file: video.mov & Error: cannot convert float NaN to integer

In [37]:
head_movement_df.head(10)

,frame,bb_x1,bb_y1,bb_x2,bb_y2,face_confidence,pitch,roll,yaw,time,bb_center_x,bb_center_y,euclidean_angle,euclidean_angle_disp,xy_disp
0,0.0,800.0,301.0,1219.0,720.0,1.0,1.419891,-0.985182,-3.258849,0.000000,1009.5,510.5,3.699389,NaN,0.000000
1,1.0,800.0,301.0,1217.0,718.0,1.0,0.981757,-1.041964,-2.896952,0.033333,1008.5,509.5,3.239309,0.460080,1.414214
2,2.0,800.0,302.0,1216.0,718.0,1.0,1.096575,-1.149379,-2.379452,0.066667,1008.0,510.0,2.870066,0.369243,0.707107
3,3.0,800.0,303.0,1214.0,717.0,1.0,0.481617,-1.429675,-2.048136,0.100000,1007.0,510.0,2.548557,0.321509,1.000000
4,4.0,800.0,304.0,1213.0,717.0,1.0,0.000315,-1.636427,-2.157406,0.133333,1006.5,510.5,2.707766,0.159209,0.707107
5,5.0,800.0,305.0,1211.0,716.0,1.0,0.129816,-1.552130,-2.138590,0.166667,1005.5,510.5,2.647029,0.060736,1.000000
6,6.0,800.0,306.0,1210.0,716.0,1.0,0.315305,-1.484749,-2.691105,0.200000,1005.0,511.0,3.093138,0.446108,0.707107
7,7.0,800.0,307.0,1208.0,715.0,1.0,0.976689,-1.254170,-3.549597,0.233333,1004.0,511.0,3.898916,0.805778,1.000000
8,8.0,800.0,308.0,1207.0,715.0,1.0,1.014314,-1.094327,-4.868611,0.266667,1003.5,511.5,5.101245,1.202329,0.707107
9,9.0,800.0,309.0,1205.0,714.0,1.0,1.204029,-1.086412,-5.430156,0.300000,1002.5,511.5,5.677899,0.576654,1.000000

In [38]:
summary_df

,xy_disp_mean,pitch_mean,yaw_mean,roll_mean,euclidean_angle_disp_mean,xy_disp_std,pitch_std,yaw_std,roll_std,euclidean_angle_disp_std
0,1.912417,-2.800372,-2.526501,3.212309,0.778276,1.267778,5.306293,3.309427,2.341416,0.75166

In [1]:
!python3 -m pip install -e /Users/pelmeshek1706/Desktop/projects/airest-face/openwillis-face

Obtaining file:///Users/pelmeshek1706/Desktop/projects/airest-face/openwillis-face
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
INFO: pip is looking at multiple versions of openwillis-face to determine which version is compatible with other requirements. This could take a while.
ERROR: Package 'openwillis-face' requires a different Python: 3.11.9 not in '<3.11,>=3.9'

# emotional expressivity

In [1]:
import sys, inspect
import openwillis.face as owf
import openwillis.face.facial_emotion as fe

print(sys.executable)
print(inspect.getfile(owf))
print(inspect.getfile(fe))

with open(inspect.getfile(fe), "r") as f:
    text = f.read()

print("patched progress logs:", "Starting emotional expressivity video pass" in text)
print("patched baseline logs:", "Starting baseline normalization with baseline video path=%s" in text)

/Users/pelmeshek1706/Desktop/projects/airest-face/.venv/bin/python
/Users/pelmeshek1706/Desktop/projects/airest-face/openwillis-face/src/openwillis/face/__init__.py
/Users/pelmeshek1706/Desktop/projects/airest-face/openwillis-face/src/openwillis/face/facial_emotion.py
patched progress logs: True
patched baseline logs: True

In [2]:
%%bash
cd /Users/pelmeshek1706/Desktop/projects/airest-face

./.venv/bin/python -u - <<'PY'
import logging
import openwillis.face as owf

logging.getLogger().setLevel(logging.INFO)

framewise, summary = owf.emotional_expressivity(
    filepath='/Users/pelmeshek1706/Desktop/projects/airest-face/video.mov',
    baseline_filepath='/Users/pelmeshek1706/Downloads/baseline (1).mp4',
    bbox_list=[],
    base_bbox_list=[],
    skip_frames=5,
    split_by_speaking=False,
    rolling_std_seconds=3,
)

print("framewise shape:", framewise.shape)
print("summary shape:", summary.shape)
PY

INFO:root:Loading Face model: retinaface
INFO:root:Loading Facial Landmark model: mobilefacenet
INFO:root:Loading facepose model: img2pose
INFO:root:Loading AU model: xgb
INFO:root:Loading emotion model: resmasknet
INFO:root:Loading Identity model: facenet
INFO:root:Starting emotional expressivity video pass path=/Users/pelmeshek1706/Desktop/projects/airest-face/video.mov total_frames=644 sampled_frames_approx=108 fps=30.000 skip_frames=5
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 626, 626]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:Emotional expressivity progress path=/Users/pelmeshek1706/Desktop/projects/airest-face/video.mov processed_sampled_frames=1 approx_total_sampled_frames=108 current_frame=0/644
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 630, 630]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 604, 604]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 622, 622]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 630, 630]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 678, 678]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 660, 660]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 630, 630]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 634, 634]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 668, 668]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:Emotional expressivity progress path=/Users/pelmeshek1706/Desktop/projects/airest-face/video.mov processed_sampled_frames=10 approx_total_sampled_frames=108 current_frame=54/644
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 634, 634]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 616, 616]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 636, 636]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 632, 632]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 626, 626]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 682, 682]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 658, 658]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 658, 658]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 632, 632]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...

Error while terminating subprocess (pid=76782):

TypeError: %d format: a real number is required, not NoneType

In [1]:
import os
os.environ["OMP_NUM_THREADS"] = "1"

In [4]:
import os
os.environ["OMP_NUM_THREADS"] = "1"

from openwillis.face.facial_emotion import get_emotion
import time

t = time.time()
df = get_emotion('/Users/pelmeshek1706/Desktop/projects/airest-face/video.mov', skip_frames=0)
print("video only:", time.time() - t, df.shape)

INFO:root:Starting emotional expressivity video pass path=/Users/pelmeshek1706/Desktop/projects/airest-face/video.mov total_frames=644 sampled_frames_approx=644 fps=30.000 skip_frames=0

INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 626, 626]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:Emotional expressivity progress path=/Users/pelmeshek1706/Desktop/projects/airest-face/video.mov processed_sampled_frames=1 approx_total_sampled_frames=644 current_frame=0/644
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 626, 626]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 632, 632]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 630, 630]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 632, 632]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 630, 630]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 630, 630]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 606, 606]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 606, 606]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 606, 606]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:Emotional expressivity progress path=/Users/pelmeshek1706/Desktop/projects/airest-face/video.mov processed_sampled_frames=10 approx_total_sampled_frames=644 current_frame=9/644
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 608, 608]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 608, 608]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 604, 604]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 606, 606]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 606, 606]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 612, 612]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 610, 610]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 612, 612]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 622, 622]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 626, 626]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:Emotional expressivity progress path=/Users/pelmeshek1706/Desktop/projects/airest-face/video.mov processed_sampled_frames=20 approx_total_sampled_frames=644 current_frame=19/644
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 628, 628]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 616, 616]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 638, 638]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 642, 642]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 630, 630]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 632, 632]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 640, 640]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 644, 644]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 658, 658]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 646, 646]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:Emotional expressivity progress path=/Users/pelmeshek1706/Desktop/projects/airest-face/video.mov processed_sampled_frames=30 approx_total_sampled_frames=644 current_frame=29/644
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 678, 678]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 642, 642]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 638, 638]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 636, 636]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 638, 638]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 656, 656]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 660, 660]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 648, 648]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 630, 630]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 628, 628]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:Emotional expressivity progress path=/Users/pelmeshek1706/Desktop/projects/airest-face/video.mov processed_sampled_frames=40 approx_total_sampled_frames=644 current_frame=39/644
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 626, 626]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 626, 626]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 630, 630]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 636, 636]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 634, 634]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 632, 632]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 632, 632]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 630, 630]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 634, 634]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 638, 638]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:Emotional expressivity progress path=/Users/pelmeshek1706/Desktop/projects/airest-face/video.mov processed_sampled_frames=50 approx_total_sampled_frames=644 current_frame=49/644
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 634, 634]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 636, 636]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 634, 634]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 646, 646]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 668, 668]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 652, 652]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 656, 656]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 656, 656]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 640, 640]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 644, 644]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:Emotional expressivity progress path=/Users/pelmeshek1706/Desktop/projects/airest-face/video.mov processed_sampled_frames=60 approx_total_sampled_frames=644 current_frame=59/644
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 634, 634]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 620, 620]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 610, 610]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 620, 620]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 630, 630]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 632, 632]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 616, 616]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 608, 608]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 614, 614]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 610, 610]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:Emotional expressivity progress path=/Users/pelmeshek1706/Desktop/projects/airest-face/video.mov processed_sampled_frames=70 approx_total_sampled_frames=644 current_frame=69/644
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 620, 620]) to 112
INFO:root:detecting aus...

video only: 290.4961910247803 (644, 30)

In [5]:
df

,frame,time,anger,disgust,fear,happiness,sadness,surprise,neutral,AU01,...,AU15,AU17,AU20,AU23,AU24,AU25,AU26,AU28,AU43,mouth_openness
0,0,0.000000,0.020597,0.001830,0.079409,1.517738,0.749379,4.446386,93.184662,0.872812,...,0.710398,0.727663,0.0,0.721901,0.480957,0.003519,0.277574,0.263249,0.109632,29.211810
1,1,0.033333,0.031589,0.003011,0.172942,1.519061,0.985807,12.806864,84.480721,0.856635,...,0.579930,0.695178,0.0,0.555218,0.514316,0.002541,0.320726,0.320496,0.114958,28.056342
2,2,0.066667,0.030668,0.002107,0.105396,1.650666,0.772516,9.326775,88.111870,0.853391,...,0.601298,0.667665,0.0,0.773270,0.465476,0.015436,0.216600,0.188339,0.116121,29.286628
3,3,0.100000,0.034800,0.002577,0.107237,1.724939,0.761303,9.941787,87.427361,0.851209,...,0.678089,0.665556,0.0,0.794155,0.359569,0.005489,0.315011,0.417089,0.115603,28.944708
4,4,0.133333,0.041168,0.002589,0.142172,1.198032,1.020151,11.485126,86.110771,0.900841,...,0.615686,0.631103,0.0,0.690264,0.528228,0.033212,0.243865,0.423761,0.093825,29.004705
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
639,639,21.300000,0.017735,0.001359,0.128778,0.861656,0.425228,41.099667,57.465576,0.893662,...,0.584253,0.718464,0.0,0.783908,0.764831,0.047829,0.121236,0.238032,0.036174,29.934447
640,640,21.333333,0.022723,0.001959,0.155708,1.180648,0.502564,41.342686,56.793713,0.931930,...,0.632083,0.699159,0.0,0.827654,0.773255,0.002259,0.115405,0.427047,0.041378,30.015276
641,641,21.366667,0.029589,0.001688,0.083930,2.425271,0.268849,47.372761,49.817917,0.922800,...,0.711282,0.572613,0.0,0.698481,0.743624,0.009037,0.140837,0.420940,0.043848,30.094325
642,642,21.400000,0.023127,0.001337,0.125639,0.791255,0.294142,68.734810,30.029694,0.886888,...,0.599693,0.610340,0.0,0.742544,0.546771,0.007554,0.138939,0.302337,0.051281,29.000260
643,643,21.433333,0.025187,0.002495,0.112069,1.297258,0.242192,63.896542,34.424244,0.917590,...,0.655224,0.565376,0.0,0.720767,0.657936,0.006225,0.226533,0.275129,0.048631,29.720197

In [ ]:
import openwillis.face as owf

framewise, summary = owf.emotional_expressivity(
	filepath = 'video.mov', 
	baseline_filepath = '/Users/pelmeshek1706/Downloads/baseline (1).mp4', 
	bbox_list = [], 
	base_bbox_list = [], 
	skip_frames = 5, 
	split_by_speaking = False, 
	rolling_std_seconds = 3)

INFO:root:Loading Face model: retinaface
INFO:root:Loading Facial Landmark model: mobilefacenet
INFO:root:Loading facepose model: img2pose
INFO:root:Loading AU model: xgb
INFO:root:Loading emotion model: resmasknet
INFO:root:Loading Identity model: facenet
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 626, 626]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 630, 630]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 604, 604]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 622, 622]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 630, 630]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 678, 678]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 660, 660]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 630, 630]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 634, 634]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 668, 668]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 634, 634]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 616, 616]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 636, 636]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 632, 632]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 626, 626]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 682, 682]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 658, 658]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 658, 658]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 632, 632]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 616, 616]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 602, 602]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 656, 656]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 670, 670]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 644, 644]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 654, 654]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 656, 656]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 668, 668]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 662, 662]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 648, 648]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 630, 630]) to 112
INFO:root:detecting aus...
INFO:root:detecting emotions...
INFO:root:detecting faces...
INFO:root:detecting landmarks...
INFO:root:RESCALING WARNING: image_operations.extract_face_from_bbox() is rescaling cropped img with shape torch.Size([3, 632, 632]) to 112
INFO:root:detecting aus...